/**
 * Product options as ES5 source, for generated runtime code that cannot import
 * from this package: the data-source product transform, the storefront cart
 * provider, and every workflow script that prices a configuration.
 *
 * ⚠️ THIRD MIRROR. The same rules exist in teleport-gui as
 * `features/e-commerce/utils/product-options/` (the editor/canvas TypeScript)
 * and `features/workflows/templates/builders/ecommerce/product-options-script.ts`
 * (`PRODUCT_OPTIONS_HELPERS`, whose text this function returns verbatim). All
 * three must agree to the cent, or the price on the product page, the price
 * added to the cart and the price stored on the order will differ.
 * `__tests__/utils/product-options.ts` runs this copy over a fixture table that
 * is byte-identical with the GUI's parity spec.
 *
 * The block: `var` / `function` only, names prefixed `__po`; no backticks, no
 * dollar-brace, no backslash, never `params` followed by a dot; no `__po`
 * function with exactly two parameters (the handler-entry resolver in
 * `teleport-plugin-next-workflows/src/nodes/types.ts` picks the first
 * two-parameter declaration); wrapped in the sentinel comments below so an
 * export-time refresh can replace it.
 */
export const PRODUCT_OPTIONS_HELPERS_OPENING = '/* tq:po-helpers:start v1 */'
export const PRODUCT_OPTIONS_HELPERS_CLOSING = '/* tq:po-helpers:end */'

export const generateProductOptionsHelperCode = (): string =>
  [
    PRODUCT_OPTIONS_HELPERS_OPENING,
    'var __poLimits = { groups: 30, values: 60, rules: 5, priceOverrides: 12, labelChars: 120, text: 500, longText: 2000, configurationChars: 8000, configurationLabelChars: 500, optionGroupsChars: 32000, uploadBytes: 4194304, maxAmount: 1000000000 };',
    'var __poTypes = ["choice", "multi-choice", "text", "long-text", "number", "toggle", "upload"];',
    // Type names an AI or an import commonly gives, as parse reads them (matched on the slug). Same table as OPTION_TYPE_ALIASES.
    'var __poTypeAliases = [["select", "choice"], ["dropdown", "choice"], ["radio", "choice"], ["single-choice", "choice"], ["pick-one", "choice"], ["swatches", "choice"], ["multiple-choice", "multi-choice"], ["multi-select", "multi-choice"], ["multiselect", "multi-choice"], ["multichoice", "multi-choice"], ["checkboxes", "multi-choice"], ["pick-several", "multi-choice"], ["string", "text"], ["short-text", "text"], ["textarea", "long-text"], ["longtext", "long-text"], ["paragraph", "long-text"], ["integer", "number"], ["quantity", "number"], ["numeric", "number"], ["boolean", "toggle"], ["switch", "toggle"], ["yes-no", "toggle"], ["yes-or-no", "toggle"], ["file", "upload"], ["file-upload", "upload"], ["image", "upload"], ["photo", "upload"]];',
    // What an upload group lets through (never SVG). Same table as PRODUCT_OPTION_UPLOAD_MIME.
    'var __poUploadMime = { image: ["image/jpeg", "image/png", "image/webp", "image/gif"], pdf: ["application/pdf"], any: ["image/jpeg", "image/png", "image/webp", "image/gif", "application/pdf"] };',
    'var __poValueTypes = ["choice", "multi-choice"];',
    'var __poPricedTypes = ["text", "long-text", "number", "toggle", "upload"];',
    'var __poSelectableTypes = ["choice", "multi-choice", "toggle"];',
    'var __poDisplays = ["buttons", "swatches", "cards"];',
    'var __poAccepts = ["image", "pdf", "any"];',
    'var __poOperators = ["is", "is-not", "is-set", "is-not-set"];',
    'var __poWarningCodes = ["CONFIGURATION_TOO_LONG", "OPTION_GROUPS_TOO_LARGE"];',
    // The validator's refusals; `{option}` and `{source}` are filled in. Same text as PRODUCT_OPTION_MESSAGES.
    'var __poMessages = {',
    '  TOO_MANY_GROUPS: "A product can have at most 30 options.",',
    '  GROUP_LABEL_REQUIRED: "{option} needs a name.",',
    '  GROUP_LABEL_TOO_LONG: "The name of “{option}” is longer than 120 characters.",',
    '  DUPLICATE_GROUP_KEY: "“{option}” uses the same internal key as an earlier option.",',
    '  CHOICE_NEEDS_VALUE: "“{option}” needs at least one choice.",',
    '  TOO_MANY_VALUES: "“{option}” can have at most 60 choices.",',
    '  VALUE_LABEL_REQUIRED: "Every choice of “{option}” needs a name.",',
    '  VALUE_LABEL_TOO_LONG: "A choice of “{option}” is longer than 120 characters.",',
    '  DUPLICATE_VALUE_KEY: "Two choices of “{option}” use the same internal key.",',
    '  VALUE_LABEL_DUPLICATE: "Two choices of “{option}” have the same name.",',
    '  MULTI_MIN_MAX: "“{option}”: the minimum number of picks is more than the maximum.",',
    '  MULTI_MAX_TOO_LOW: "“{option}”: allow at least one pick, or leave the maximum empty for no limit.",',
    '  MULTI_TOO_FEW_VALUES: "“{option}” asks for more picks than it has choices.",',
    '  MULTI_DEFAULTS_TOO_MANY: "“{option}” pre-selects more choices than shoppers may pick. Pre-select fewer, or raise the maximum.",',
    '  TEXT_MAX_LENGTH: "“{option}”: the character limit must be between 1 and 500.",',
    '  LONG_TEXT_MAX_LENGTH: "“{option}”: the character limit must be between 1 and 2000.",',
    '  NUMBER_MIN_MAX: "“{option}”: the minimum is more than the maximum.",',
    '  NUMBER_STEP: "“{option}”: the step must be more than 0.",',
    '  NUMBER_DEFAULT_RANGE: "“{option}”: the starting value must be between the minimum and the maximum.",',
    '  NUMBER_DEFAULT_STEP: "“{option}”: the starting value must be a whole number of steps from the minimum.",',
    '  PRICE_AMOUNT_INVALID: "Prices on “{option}” must be between 0 and 1,000,000,000.",',
    '  PRICE_PERCENT_RANGE: "A percentage on “{option}” must be between 0 and 1000.",',
    '  PRICE_PER_UNIT_NUMBER_ONLY: "Only a number option can be priced per unit, so “{option}” cannot.",',
    '  PRICE_TOO_MANY_OVERRIDES: "“{option}” can have at most 12 prices that depend on other options.",',
    '  PRICE_SOURCE_MISSING: "A price on “{option}” depends on an option that no longer exists.",',
    '  PRICE_SOURCE_LATER: "A price on “{option}” depends on “{source}”, which comes after it. Move “{source}” above “{option}”.",',
    '  PRICE_SOURCE_TYPE: "A price on “{option}” can only depend on a pick-one, pick-several or yes-or-no option.",',
    '  PRICE_SOURCE_VALUES: "A price on “{option}” depends on a choice of “{source}” that no longer exists.",',
    '  VISIBILITY_TOO_MANY_RULES: "“{option}” can have at most 5 rules for when it is shown.",',
    '  VISIBILITY_SOURCE_MISSING: "“{option}” is shown depending on an option that no longer exists.",',
    '  VISIBILITY_SOURCE_LATER: "“{option}” is shown depending on “{source}”, which comes after it. Move “{source}” above “{option}”.",',
    '  VISIBILITY_SOURCE_TYPE: "“{option}” can only be shown depending on a pick-one, pick-several or yes-or-no option.",',
    '  VISIBILITY_SOURCE_VALUES: "“{option}” is shown depending on a choice of “{source}” that no longer exists.",',
    '  GIFT_CARD_OPTIONS_PRICE: "Gift cards can have options, but not prices on them. Set every option to no extra charge.",',
    '  RECURRING_OPTIONS_PRICE: "Subscription products can have options, but not prices on them. Set every option to no extra charge.",',
    '  CONFIGURATION_TOO_LONG: "Filled in to their limits, these options could exceed 8000 characters and be refused at checkout. Use fewer options, or lower the character limits of the text options.",',
    '  OPTION_GROUPS_TOO_LARGE: "These options take more than 32000 characters to save. Use fewer choices or shorter descriptions.",',
    '  OPTIONS_UNREADABLE: "The options could not be read. Send them as a list of options, each with a name and a type.",',
    '  OPTION_TYPE_UNKNOWN: "“{option}” has a type that does not exist. Use pick one, pick several, short text, long text, number, yes or no, or file upload.",',
    '  VALUE_UNREADABLE: "A choice of “{option}” could not be read. Give every choice a name.",',
    '  PRICE_UNREADABLE: "A price on “{option}” could not be read. Use a fixed amount or a percentage (an amount per unit only on a number option), and put the prices of a pick-one or pick-several option on its choices.",',
    '  VISIBILITY_RULE_UNREADABLE: "A rule for when “{option}” is shown could not be read. Use is, is not, is set or is not set on an earlier option."',
    '};',
    // Primitive readers. Every value arrives from JSON, a driver or the DOM, so nothing is trusted.
    'function __poRound2(n) { return Math.round(n * 100) / 100; }',
    'function __poIsObject(v) { return v !== null && typeof v === "object" && !Array.isArray(v); }',
    'function __poFinite(v) {',
    '  if (typeof v === "number") { return isFinite(v) ? v : undefined; }',
    '  if (typeof v === "string" && v.trim() !== "") {',
    '    var parsed = Number(v.trim());',
    '    return isFinite(parsed) ? parsed : undefined;',
    '  }',
    '  return undefined;',
    '}',
    'function __poSafe(v) {',
    '  var parsed = __poFinite(v);',
    '  return parsed === undefined ? 0 : parsed;',
    '}',
    'function __poText(v) {',
    '  if (typeof v === "string") { return v; }',
    '  if (typeof v === "number" && isFinite(v)) { return String(v); }',
    '  return "";',
    '}',
    'function __poFlag(v) {',
    '  if (v === true || v === 1) { return true; }',
    '  if (typeof v === "string") {',
    '    var s = v.trim().toLowerCase();',
    '    return s === "true" || s === "t" || s === "1" || s === "yes" || s === "on";',
    '  }',
    '  return false;',
    '}',
    // Cuts to max UTF-16 units; a cut that would split a surrogate pair (55296-56319 = a high half) keeps one unit less.
    'function __poClip(text, max, ellipsis) {',
    '  if (text.length <= max) { return text; }',
    '  var end = ellipsis ? max - 1 : max;',
    '  var last = end > 0 ? text.charCodeAt(end - 1) : 0;',
    '  if (last >= 55296 && last <= 56319) { end -= 1; }',
    '  return ellipsis ? text.slice(0, end) + "…" : text.slice(0, end);',
    '}',
    // Collapses runs of spaces, control characters (<= 32, 127-159) and U+2028 / U+2029 into one space, trimming the ends (no regex: no backslashes allowed).
    'function __poOneLine(text) {',
    '  var out = "";',
    '  var pending = false;',
    '  for (var i = 0; i < text.length; i++) {',
    '    var code = text.charCodeAt(i);',
    '    if (code <= 32 || (code >= 127 && code <= 159) || code === 8232 || code === 8233) { pending = out.length > 0; continue; }',
    '    if (pending) { out += " "; pending = false; }',
    '    out += text.charAt(i);',
    '  }',
    '  return out;',
    '}',
    'function __poSlug(text) {',
    '  return String(text).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").substring(0, 200);',
    '}',
    'function __poWhole(v) {',
    '  var parsed = __poFinite(v);',
    '  return parsed === undefined ? undefined : Math.max(0, Math.floor(parsed));',
    '}',
    'function __poWith(base, field, value) {',
    '  var out = {};',
    '  for (var k in base) { if (Object.prototype.hasOwnProperty.call(base, k)) { out[k] = base[k]; } }',
    '  out[field] = value;',
    '  return out;',
    '}',
    // Keys: the slug of the label (or the fallback), then -2, -3, ... until free.
    'function __poMintKey(label, taken, fallback) {',
    '  var list = Array.isArray(taken) ? taken : [];',
    '  var base = __poSlug(typeof label === "string" ? label : "") || (fallback || "option");',
    '  if (list.indexOf(base) === -1) { return base; }',
    '  var suffix = 2;',
    '  while (list.indexOf(base + "-" + suffix) !== -1) { suffix++; }',
    '  return base + "-" + suffix;',
    '}',
    'function __poSourceValueKeys(group) {',
    '  if (group.type === "toggle") { return ["on"]; }',
    '  var values = Array.isArray(group.values) ? group.values : [];',
    '  var out = [];',
    '  for (var i = 0; i < values.length; i++) { if (__poIsObject(values[i])) { out.push(values[i].key); } }',
    '  return out;',
    '}',
    'function __poFindGroup(groups, key, types) {',
    '  for (var i = 0; i < groups.length; i++) {',
    '    if (groups[i].key === key) { return !types || types.indexOf(groups[i].type) !== -1 ? groups[i] : null; }',
    '  }',
    '  return null;',
    '}',
    // Parsing option_groups: total, clamped, keys minted, rules kept only when they point at EARLIER selectable groups.
    'function __poAmount(n) { return isFinite(n) && n > 0 ? Math.min(__poLimits.maxAmount, n) : 0; }',
    'function __poParseRule(raw) {',
    '  if (typeof raw === "number") { return { mode: "fixed", amount: __poAmount(raw) }; }',
    '  if (typeof raw === "string") {',
    '    var bare = __poFinite(raw);',
    '    return bare === undefined ? { mode: "none" } : { mode: "fixed", amount: __poAmount(bare) };',
    '  }',
    '  if (!__poIsObject(raw)) { return { mode: "none" }; }',
    '  if (raw.mode === "fixed") { return { mode: "fixed", amount: __poAmount(__poSafe(raw.amount)) }; }',
    '  if (raw.mode === "percent") { return { mode: "percent", percent: Math.min(1000, Math.max(0, __poSafe(raw.percent))) }; }',
    '  if (raw.mode === "per-unit") { return { mode: "per-unit", amount: __poAmount(__poSafe(raw.amount)) }; }',
    '  return { mode: "none" };',
    '}',
    // The type a group means (readOptionGroupType), or null: exact, then its slug, then a synonym.
    'function __poReadType(raw) {',
    '  var hasValues = Array.isArray(raw.values) && raw.values.length > 0;',
    '  if (__poTypes.indexOf(raw.type) !== -1) { return raw.type; }',
    '  var slug = __poSlug(__poText(raw.type));',
    '  if (slug === "") { return null; }',
    '  if (__poTypes.indexOf(slug) !== -1) { return slug; }',
    '  if (slug === "checkbox") { return hasValues ? "multi-choice" : "toggle"; }',
    '  for (var i = 0; i < __poTypeAliases.length; i++) {',
    '    if (__poTypeAliases[i][0] === slug) { return __poTypeAliases[i][1] === "upload" && hasValues ? "choice" : __poTypeAliases[i][1]; }',
    '  }',
    '  return null;',
    '}',
    'function __poUnitless(rule) {',
    '  return rule.mode === "per-unit" ? { mode: "fixed", amount: rule.amount } : rule;',
    '}',
    'function __poRuleSource(item, earlier, needsValues) {',
    '  var groupKey = __poSlug(__poText(item.groupKey));',
    '  var source = __poFindGroup(earlier, groupKey, __poSelectableTypes);',
    '  if (!source) { return null; }',
    '  var allowed = __poSourceValueKeys(source);',
    '  var listed = Array.isArray(item.valueKeys) ? item.valueKeys : (typeof item.valueKeys === "string" ? [item.valueKeys] : []);',
    '  var valueKeys = [];',
    '  for (var i = 0; i < listed.length; i++) {',
    '    var valueKey = __poSlug(__poText(listed[i]));',
    '    if (allowed.indexOf(valueKey) !== -1 && valueKeys.indexOf(valueKey) === -1) { valueKeys.push(valueKey); }',
    '  }',
    '  if (needsValues && valueKeys.length === 0) { return null; }',
    '  return { groupKey: groupKey, valueKeys: valueKeys };',
    '}',
    'function __poParseOverrides(raw, earlier, allowPerUnit) {',
    '  if (!Array.isArray(raw)) { return []; }',
    '  var out = [];',
    '  for (var i = 0; i < raw.length; i++) {',
    '    if (out.length >= __poLimits.priceOverrides) { break; }',
    '    var item = raw[i];',
    '    if (!__poIsObject(item)) { continue; }',
    '    var source = __poRuleSource(item, earlier, true);',
    '    if (!source) { continue; }',
    '    var price = __poParseRule(item.price);',
    '    out.push({ groupKey: source.groupKey, valueKeys: source.valueKeys, price: allowPerUnit ? price : __poUnitless(price) });',
    '  }',
    '  return out;',
    '}',
    'function __poParseVisibility(raw, earlier, limit) {',
    '  if (!Array.isArray(raw)) { return []; }',
    '  var out = [];',
    '  for (var i = 0; i < raw.length; i++) {',
    '    if (out.length >= limit) { break; }',
    '    var item = raw[i];',
    '    if (!__poIsObject(item) || __poOperators.indexOf(item.operator) === -1) { continue; }',
    '    var operator = item.operator;',
    '    var needsValues = operator === "is" || operator === "is-not";',
    '    var source = __poRuleSource(item, earlier, needsValues);',
    '    if (!source) { continue; }',
    '    out.push(needsValues ? { groupKey: source.groupKey, operator: operator, valueKeys: source.valueKeys } : { groupKey: source.groupKey, operator: operator });',
    '  }',
    '  return out;',
    '}',
    // Every stored string is trimmed, clipped, then trimmed again (a clip landing on a space leaves nothing a second parse would change).
    'function __poParseValue(raw, taken, earlier) {',
    '  if (!__poIsObject(raw)) { return null; }',
    '  var label = __poClip(__poText(raw.label).trim(), __poLimits.labelChars, false).trim();',
    '  var value = { key: __poMintKey(__poSlug(__poText(raw.key)) || label, taken, "value"), label: label, price: __poUnitless(__poParseRule(raw.price)) };',
    '  var description = __poClip(__poText(raw.description).trim(), __poLimits.text, false).trim();',
    '  var color = __poClip(__poText(raw.color).trim(), 64, false).trim();',
    '  var imageUrl = __poClip(__poText(raw.imageUrl).trim(), 2048, false).trim();',
    '  if (description) { value.description = description; }',
    '  if (color) { value.color = color; }',
    '  if (imageUrl) { value.imageUrl = imageUrl; }',
    '  if (__poFlag(raw["default"])) { value["default"] = true; }',
    '  var overrides = __poParseOverrides(raw.priceWhen, earlier, false);',
    '  if (overrides.length > 0) { value.priceWhen = overrides; }',
    '  return value;',
    '}',
    'function __poParseValues(rawValues, earlier, type) {',
    '  var values = [];',
    '  var taken = [];',
    '  for (var i = 0; i < rawValues.length; i++) {',
    '    if (values.length >= __poLimits.values) { break; }',
    '    var value = __poParseValue(rawValues[i], taken, earlier);',
    '    if (value) { values.push(value); taken.push(value.key); }',
    '  }',
    '  if (type === "choice") {',
    '    var seen = false;',
    '    for (var j = 0; j < values.length; j++) {',
    '      if (values[j]["default"] && seen) { delete values[j]["default"]; }',
    '      else if (values[j]["default"]) { seen = true; }',
    '    }',
    '  }',
    '  return values;',
    '}',
    'function __poParseGroup(raw, earlier, taken) {',
    '  if (!__poIsObject(raw)) { return null; }',
    '  var label = __poClip(__poText(raw.label).trim(), __poLimits.labelChars, false).trim();',
    '  var rawValues = Array.isArray(raw.values) ? raw.values : [];',
    '  var type = __poReadType(raw) || (rawValues.length > 0 ? "choice" : "text");',
    '  var group = { key: __poMintKey(__poSlug(__poText(raw.key)) || label, taken, "option"), label: label, type: type, required: type === "toggle" ? false : __poFlag(raw.required) };',
    '  var helpText = __poClip(__poText(raw.helpText).trim(), __poLimits.text, false).trim();',
    '  if (helpText) { group.helpText = helpText; }',
    '  if (__poValueTypes.indexOf(type) !== -1) {',
    '    group.display = __poDisplays.indexOf(raw.display) !== -1 ? raw.display : "buttons";',
    '    group.values = __poParseValues(rawValues, earlier, type);',
    '    if (type === "multi-choice") {',
    '      var minSelected = __poWhole(raw.minSelected);',
    '      var maxSelected = __poWhole(raw.maxSelected);',
    '      if (minSelected !== undefined) { group.minSelected = minSelected; }',
    '      if (maxSelected !== undefined && maxSelected >= 1) { group.maxSelected = maxSelected; }',
    '    }',
    '  }',
    '  if (type === "text" || type === "long-text" || type === "number") {',
    '    var placeholder = __poClip(__poText(raw.placeholder).trim(), __poLimits.labelChars, false).trim();',
    '    if (placeholder) { group.placeholder = placeholder; }',
    '  }',
    '  if (type === "text" || type === "long-text") {',
    '    var maxLength = __poWhole(raw.maxLength);',
    '    if (maxLength !== undefined) { group.maxLength = Math.min(type === "text" ? __poLimits.text : __poLimits.longText, Math.max(1, maxLength)); }',
    '  }',
    '  if (type === "number") {',
    '    var min = __poFinite(raw.min);',
    '    var max = __poFinite(raw.max);',
    '    var step = __poFinite(raw.step);',
    '    var unit = __poClip(__poText(raw.unit).trim(), __poLimits.labelChars, false).trim();',
    '    var defaultValue = __poFinite(raw.defaultValue);',
    '    if (min !== undefined) { group.min = min; }',
    '    if (max !== undefined) { group.max = max; }',
    '    if (step !== undefined && step > 0) { group.step = step; }',
    '    if (unit) { group.unit = unit; }',
    '    if (defaultValue !== undefined) { group.defaultValue = defaultValue; }',
    '  }',
    '  if (__poPricedTypes.indexOf(type) !== -1) {',
    '    var price = __poParseRule(raw.price);',
    '    group.price = type === "number" ? price : __poUnitless(price);',
    '    var overrides = __poParseOverrides(raw.priceWhen, earlier, type === "number");',
    '    if (overrides.length > 0) { group.priceWhen = overrides; }',
    '  }',
    '  if (type === "upload") {',
    '    group.accept = __poAccepts.indexOf(raw.accept) !== -1 ? raw.accept : "any";',
    '    group.maxFiles = 1;',
    '  }',
    '  var visibleWhen = __poParseVisibility(raw.visibleWhen, earlier, __poLimits.rules);',
    '  if (visibleWhen.length > 0) { group.visibleWhen = visibleWhen; }',
    '  return group;',
    '}',
    'function __poParseGroups(raw) {',
    '  var source = raw;',
    '  if (typeof source === "string") {',
    '    var trimmed = source.trim();',
    '    if (trimmed === "") { return []; }',
    '    try { source = JSON.parse(trimmed); } catch (e) { return []; }',
    '  }',
    '  if (!Array.isArray(source)) { return []; }',
    '  var groups = [];',
    '  var taken = [];',
    '  for (var i = 0; i < source.length; i++) {',
    '    if (groups.length >= __poLimits.groups) { break; }',
    '    var group = __poParseGroup(source[i], groups, taken);',
    '    if (group) { groups.push(group); taken.push(group.key); }',
    '  }',
    '  return groups;',
    '}',
    // Serializing: one key order, so the same groups always give the same text; empty is null.
    'function __poObjectLike(v) { return v !== null && typeof v === "object"; }',
    'function __poCopy(target, source, fields) {',
    '  for (var i = 0; i < fields.length; i++) {',
    '    var v = source[fields[i]];',
    '    if (v !== undefined && v !== null) { target[fields[i]] = v; }',
    '  }',
    '  return target;',
    '}',
    'function __poOrderRule(rule) {',
    '  if (!rule || typeof rule !== "object") { return { mode: "none" }; }',
    '  if (rule.mode === "percent") { return { mode: "percent", percent: rule.percent }; }',
    '  if (rule.mode === "fixed" || rule.mode === "per-unit") { return { mode: rule.mode, amount: rule.amount }; }',
    '  return { mode: "none" };',
    '}',
    'function __poOrderOverride(override) {',
    '  return { groupKey: override.groupKey, valueKeys: Array.isArray(override.valueKeys) ? override.valueKeys.slice() : [], price: __poOrderRule(override.price) };',
    '}',
    'function __poOrderOverrides(list) {',
    '  var out = [];',
    '  for (var i = 0; i < list.length; i++) { if (__poObjectLike(list[i])) { out.push(__poOrderOverride(list[i])); } }',
    '  return out;',
    '}',
    'function __poOrderVisibility(rule) {',
    '  var out = { groupKey: rule.groupKey, operator: rule.operator };',
    '  if (Array.isArray(rule.valueKeys)) { out.valueKeys = rule.valueKeys.slice(); }',
    '  return out;',
    '}',
    'function __poOrderValue(value) {',
    '  var out = __poCopy({}, value, ["key", "label", "description", "color", "imageUrl"]);',
    '  out.price = __poOrderRule(value.price);',
    '  if (value["default"] === true) { out["default"] = true; }',
    '  if (Array.isArray(value.priceWhen)) { out.priceWhen = __poOrderOverrides(value.priceWhen); }',
    '  return out;',
    '}',
    'function __poOrderGroup(group) {',
    '  var out = __poCopy({}, group, ["key", "label", "type"]);',
    '  out.required = group.required === true;',
    '  __poCopy(out, group, ["helpText", "display"]);',
    '  if (Array.isArray(group.values)) {',
    '    var values = [];',
    '    for (var i = 0; i < group.values.length; i++) { if (__poObjectLike(group.values[i])) { values.push(__poOrderValue(group.values[i])); } }',
    '    out.values = values;',
    '  }',
    '  __poCopy(out, group, ["minSelected", "maxSelected", "placeholder", "maxLength", "min", "max", "step", "unit", "defaultValue"]);',
    '  if (group.price) { out.price = __poOrderRule(group.price); }',
    '  if (Array.isArray(group.priceWhen)) { out.priceWhen = __poOrderOverrides(group.priceWhen); }',
    '  __poCopy(out, group, ["accept", "maxFiles"]);',
    '  if (Array.isArray(group.visibleWhen)) {',
    '    var rules = [];',
    '    for (var r = 0; r < group.visibleWhen.length; r++) { if (__poObjectLike(group.visibleWhen[r])) { rules.push(__poOrderVisibility(group.visibleWhen[r])); } }',
    '    out.visibleWhen = rules;',
    '  }',
    '  return out;',
    '}',
    'function __poSerialize(groups) {',
    '  var present = [];',
    '  if (Array.isArray(groups)) {',
    '    for (var i = 0; i < groups.length; i++) { if (__poObjectLike(groups[i])) { present.push(__poOrderGroup(groups[i])); } }',
    '  }',
    '  return present.length === 0 ? null : JSON.stringify(present);',
    '}',
    // Uploaded files: https only (no javascript: or data: links), bounded fields, an id of letters, digits, _ . - (not only dots).
    'function __poIsFileRef(ref) {',
    '  if (!ref || typeof ref !== "object" || Array.isArray(ref)) { return false; }',
    '  var url = ref.url;',
    '  if (typeof url !== "string" || url.length <= 8 || url.length > 2048) { return false; }',
    '  if (url.slice(0, 8).toLowerCase() !== "https://") { return false; }',
    '  if (typeof ref.id !== "string" || !/^[A-Za-z0-9_.-]{1,128}$/.test(ref.id) || !/[A-Za-z0-9_-]/.test(ref.id)) { return false; }',
    '  if (typeof ref.name !== "string" || ref.name.length > 255) { return false; }',
    '  if (typeof ref.mimeType !== "string" || ref.mimeType.length > 100) { return false; }',
    '  return typeof ref.size === "number" && isFinite(ref.size) && ref.size >= 0;',
    '}',
    'function __poFileRef(raw) {',
    '  var source = raw && typeof raw === "object" ? raw : {};',
    '  var size = -1;',
    '  if (typeof source.size === "number" && isFinite(source.size)) { size = source.size; }',
    '  else if (typeof source.size === "string" && source.size.trim() !== "") {',
    '    var parsed = Number(source.size.trim());',
    '    size = isFinite(parsed) ? parsed : -1;',
    '  }',
    '  return { id: typeof source.id === "string" ? source.id : "", name: typeof source.name === "string" ? source.name : "", size: size, url: typeof source.url === "string" ? source.url : "", mimeType: typeof source.mimeType === "string" ? source.mimeType : "" };',
    '}',
    // Whether a stored file renders as a thumbnail rather than a plain link (isImageFileRef).
    'function __poIsImage(ref) { return __poIsObject(ref) && typeof ref.mimeType === "string" && ref.mimeType.toLowerCase().indexOf("image/") === 0; }',
    // Configurations: [{key, value}] as a cart line carries them.
    'function __poEntryValue(value) {',
    '  if (typeof value === "string" || typeof value === "boolean") { return value; }',
    '  if (typeof value === "number") { return isFinite(value) ? value : undefined; }',
    '  if (Array.isArray(value)) {',
    '    var out = [];',
    '    if (value.length > 0 && __poIsObject(value[0])) {',
    '      for (var i = 0; i < value.length; i++) { if (__poIsObject(value[i])) { out.push(__poFileRef(value[i])); } }',
    '      return out;',
    '    }',
    '    for (var j = 0; j < value.length; j++) {',
    '      if (typeof value[j] === "string" || (typeof value[j] === "number" && isFinite(value[j]))) { out.push(__poText(value[j])); }',
    '    }',
    '    return out;',
    '  }',
    '  if (__poIsObject(value)) { return [__poFileRef(value)]; }',
    '  return undefined;',
    '}',
    'function __poParseEntries(raw) {',
    '  var source = raw;',
    '  if (typeof source === "string") {',
    '    var trimmed = source.trim();',
    '    if (trimmed === "") { return []; }',
    '    try { source = JSON.parse(trimmed); } catch (e) { return []; }',
    '  }',
    '  if (!Array.isArray(source)) { return []; }',
    '  var entries = [];',
    '  var seen = [];',
    '  for (var i = 0; i < source.length; i++) {',
    '    var item = source[i];',
    '    if (!__poIsObject(item)) { continue; }',
    '    var key = __poText(item.key).trim();',
    '    if (key === "" || seen.indexOf(key) !== -1) { continue; }',
    '    var value = __poEntryValue(item.value);',
    '    if (value === undefined) { continue; }',
    '    entries.push({ key: key, value: value });',
    '    seen.push(key);',
    '  }',
    '  return entries;',
    '}',
    'function __poCanonicalValue(value) {',
    '  if (typeof value === "string") {',
    '    var trimmed = value.trim();',
    '    return trimmed === "" ? undefined : trimmed;',
    '  }',
    '  if (typeof value === "boolean") { return value ? true : undefined; }',
    '  if (typeof value === "number") { return value; }',
    '  if (value.length === 0) { return undefined; }',
    '  var out = [];',
    '  var i;',
    '  if (typeof value[0] === "object") {',
    '    for (i = 0; i < value.length; i++) { out.push({ id: value[i].id, name: value[i].name, size: value[i].size, url: value[i].url, mimeType: value[i].mimeType }); }',
    '    return out;',
    '  }',
    '  for (i = 0; i < value.length; i++) {',
    '    var key = value[i].trim();',
    '    if (key !== "" && out.indexOf(key) === -1) { out.push(key); }',
    '  }',
    '  return out.length > 0 ? out.sort() : undefined;',
    '}',
    'function __poSortByKey(list) {',
    '  for (var i = 1; i < list.length; i++) {',
    '    var item = list[i];',
    '    var j = i - 1;',
    '    while (j >= 0 && list[j].key > item.key) { list[j + 1] = list[j]; j--; }',
    '    list[j + 1] = item;',
    '  }',
    '  return list;',
    '}',
    'function __poCanonicalEntries(raw) {',
    '  var parsed = __poParseEntries(raw);',
    '  var out = [];',
    '  for (var i = 0; i < parsed.length; i++) {',
    '    var value = __poCanonicalValue(parsed[i].value);',
    '    if (value !== undefined) { out.push({ key: parsed[i].key, value: value }); }',
    '  }',
    '  return __poSortByKey(out);',
    '}',
    'function __poCanonical(entries) {',
    '  var list = __poCanonicalEntries(entries);',
    '  return list.length === 0 ? "" : JSON.stringify(list);',
    '}',
    // The line key hashes this form: an upload reduced to its file ids, so renaming the file keeps the line.
    'function __poCanonicalForKey(entries) {',
    '  var list = __poCanonicalEntries(entries);',
    '  if (list.length === 0) { return ""; }',
    '  var out = [];',
    '  for (var i = 0; i < list.length; i++) {',
    '    var value = list[i].value;',
    '    if (Array.isArray(value) && value.length > 0 && typeof value[0] === "object") {',
    '      var ids = [];',
    '      for (var j = 0; j < value.length; j++) { ids.push(value[j].id); }',
    '      value = ids;',
    '    }',
    '    out.push({ key: list[i].key, value: value });',
    '  }',
    '  return JSON.stringify(out);',
    '}',
    'function __poHex8(n) { return ("0000000" + n.toString(16)).slice(-8); }',
    // djb2 and FNV-1a over the UTF-16 code units: 16 lowercase hex characters.
    'function __poHash(text) {',
    '  var djb = 5381;',
    '  var fnv = 2166136261;',
    '  for (var i = 0; i < text.length; i++) {',
    '    var code = text.charCodeAt(i);',
    '    djb = ((djb << 5) + djb + code) >>> 0;',
    '    fnv = (fnv ^ code) >>> 0;',
    '    fnv = ((fnv << 24) + fnv * 403) >>> 0;',
    '  }',
    '  return __poHex8(djb) + __poHex8(fnv);',
    '}',
    'function __poKey(entries) {',
    '  var text = __poCanonicalForKey(entries);',
    '  return text === "" ? "" : __poHash(text);',
    '}',
    // Defaults: a pick-one default, the pick-several defaults, a number starting value.
    'function __poDefaultSelection(groups) {',
    '  var selection = {};',
    '  var list = Array.isArray(groups) ? groups : [];',
    '  for (var i = 0; i < list.length; i++) {',
    '    var group = list[i];',
    '    if (!__poIsObject(group)) { continue; }',
    '    var values = Array.isArray(group.values) ? group.values : [];',
    '    var j;',
    '    if (group.type === "choice") {',
    '      for (j = 0; j < values.length; j++) { if (__poIsObject(values[j]) && values[j]["default"] === true) { selection[group.key] = values[j].key; break; } }',
    '    } else if (group.type === "multi-choice") {',
    '      var keys = [];',
    '      for (j = 0; j < values.length; j++) { if (__poIsObject(values[j]) && values[j]["default"] === true) { keys.push(values[j].key); } }',
    '      if (keys.length > 0) { selection[group.key] = keys; }',
    '    } else if (group.type === "number" && typeof group.defaultValue === "number" && isFinite(group.defaultValue)) {',
    '      selection[group.key] = group.defaultValue;',
    '    }',
    '  }',
    '  return selection;',
    '}',
    'function __poEntriesFromSelection(selection) {',
    '  if (!__poIsObject(selection)) { return []; }',
    '  var entries = [];',
    '  var keys = Object.keys(selection);',
    '  for (var i = 0; i < keys.length; i++) {',
    '    var value = selection[keys[i]];',
    '    if (value !== undefined && value !== null) { entries.push({ key: keys[i], value: value }); }',
    '  }',
    '  return entries;',
    '}',
    'function __poDefaultEntries(groups) { return __poEntriesFromSelection(__poDefaultSelection(groups)); }',
    // Pricing: a price override applies while its EARLIER source group is shown and set to one of its values.
    // Answers are read from own properties only, so a group keyed constructor is unanswered until answered.
    'function __poSelectionIncludes(selection, groupKey, valueKeys) {',
    '  var current = Object.prototype.hasOwnProperty.call(selection, groupKey) ? selection[groupKey] : undefined;',
    '  var wanted = Array.isArray(valueKeys) ? valueKeys : [];',
    '  if (current === true) { return wanted.indexOf("on") !== -1; }',
    '  if (typeof current === "string") { return wanted.indexOf(current) !== -1; }',
    '  if (Array.isArray(current)) {',
    '    for (var i = 0; i < current.length; i++) { if (typeof current[i] === "string" && wanted.indexOf(current[i]) !== -1) { return true; } }',
    '  }',
    '  return false;',
    '}',
    // The price variant in force: the index of the first matching override, else "d" (the default price). The last segment of a pv: key.
    'function __poEffectiveVariant(target, selection, visibleKeys) {',
    '  var overrides = target && Array.isArray(target.priceWhen) ? target.priceWhen : [];',
    '  var visible = Array.isArray(visibleKeys) ? visibleKeys : [];',
    '  for (var i = 0; i < overrides.length; i++) {',
    '    var override = overrides[i];',
    '    if (override && visible.indexOf(override.groupKey) !== -1 && __poSelectionIncludes(selection || {}, override.groupKey, override.valueKeys)) { return i; }',
    '  }',
    '  return "d";',
    '}',
    'function __poEffectiveRule(target, selection, visibleKeys) {',
    '  var variant = __poEffectiveVariant(target, selection, visibleKeys);',
    '  var rule = variant === "d" ? (target ? target.price : undefined) : target.priceWhen[variant].price;',
    '  return rule && typeof rule === "object" ? rule : { mode: "none" };',
    '}',
    // pv:pid|gk|vk|<i or d> for a value; valueKey null / undefined gives pv:pid|gk|<i or d> for a priced group (priceVariantActiveKey).
    'function __poPriceVariantKey(productId, groupKey, valueKey, variant) {',
    '  var scope = valueKey === null || valueKey === undefined ? productId + "|" + groupKey : productId + "|" + groupKey + "|" + valueKey;',
    '  return "pv:" + scope + "|" + variant;',
    '}',
    // A negative quantity priced per unit gives NaN, which the resolver refuses as out-of-range.
    'function __poRuleDelta(rule, base, quantity) {',
    '  var delta = 0;',
    '  if (rule.mode === "fixed") { delta = __poRound2(Math.max(0, __poSafe(rule.amount))); }',
    '  else if (rule.mode === "percent") {',
    '    var percent = Math.min(1000, Math.max(0, __poSafe(rule.percent)));',
    '    delta = __poRound2(base * percent / 100);',
    '  } else if (rule.mode === "per-unit") { delta = quantity < 0 ? NaN : __poRound2(Math.max(0, __poSafe(rule.amount)) * quantity); }',
    '  return Math.max(0, delta);',
    '}',
    // Whether a number falls between two steps counted from min (else 0), with a relative tolerance (isNumberOffStep).
    'function __poOffStep(step, min, number) {',
    '  if (typeof step !== "number" || !(step > 0) || !isFinite(step)) { return false; }',
    '  var origin = typeof min === "number" && isFinite(min) ? min : 0;',
    '  var steps = (number - origin) / step;',
    '  return Math.abs(steps - Math.round(steps)) > 1e-9 * Math.max(1, Math.abs(steps));',
    '}',
    'function __poIsVisible(group, selection, visibleKeys) {',
    '  var rules = Array.isArray(group.visibleWhen) ? group.visibleWhen : [];',
    '  for (var i = 0; i < rules.length; i++) {',
    '    var rule = rules[i];',
    '    if (!__poIsObject(rule)) { continue; }',
    '    var current = Object.prototype.hasOwnProperty.call(selection, rule.groupKey) ? selection[rule.groupKey] : undefined;',
    '    var answered = visibleKeys.indexOf(rule.groupKey) !== -1 && current !== undefined && current !== null;',
    '    var holds = true;',
    '    if (rule.operator === "is") { holds = answered && __poSelectionIncludes(selection, rule.groupKey, rule.valueKeys); }',
    '    else if (rule.operator === "is-not") { holds = !(answered && __poSelectionIncludes(selection, rule.groupKey, rule.valueKeys)); }',
    '    else if (rule.operator === "is-set") { holds = answered; }',
    '    else if (rule.operator === "is-not-set") { holds = !answered; }',
    '    if (!holds) { return false; }',
    '  }',
    '  return true;',
    '}',
    'function __poValueKeysOf(values) {',
    '  var keys = [];',
    '  for (var i = 0; i < values.length; i++) { if (__poIsObject(values[i])) { keys.push(values[i].key); } }',
    '  return keys;',
    '}',
    // One group's answer, checked; null means unanswered. Problems are pushed as code:groupKey.
    'function __poReadAnswer(group, raw, errors) {',
    '  if (raw === undefined) { return null; }',
    '  var values = Array.isArray(group.values) ? group.values : [];',
    '  var tag = ":" + group.key;',
    '  var i;',
    '  if (group.type === "choice" || group.type === "multi-choice") {',
    '    var known = __poValueKeysOf(values);',
    '    var listed = Array.isArray(raw) ? raw : [raw];',
    '    var picked = [];',
    '    for (i = 0; i < listed.length; i++) {',
    '      var key = __poText(listed[i]).trim();',
    '      if (key === "") { continue; }',
    '      if (known.indexOf(key) === -1) { if (errors.indexOf("unknown-value" + tag) === -1) { errors.push("unknown-value" + tag); } }',
    '      else if (picked.indexOf(key) === -1) { picked.push(key); }',
    '    }',
    '    if (picked.length === 0) { return null; }',
    '    var ordered = [];',
    '    var valueKeys = [];',
    '    var labels = [];',
    '    for (i = 0; i < values.length; i++) {',
    '      if (__poIsObject(values[i]) && picked.indexOf(values[i].key) !== -1) { ordered.push(values[i]); valueKeys.push(values[i].key); labels.push(__poText(values[i].label) || values[i].key); }',
    '    }',
    '    if (group.type === "choice") {',
    '      if (valueKeys.length > 1) { errors.push("too-many" + tag); }',
    '      return { selection: valueKeys[0], canonical: valueKeys[0], value: valueKeys[0], valueLabel: __poText(ordered[0].label) || valueKeys[0], valueKeys: [valueKeys[0]] };',
    '    }',
    '    var minSelected = Math.max(group.required ? 1 : 0, __poSafe(group.minSelected));',
    '    if (valueKeys.length < minSelected) { errors.push("too-few" + tag); }',
    '    if (typeof group.maxSelected === "number" && valueKeys.length > group.maxSelected) { errors.push("too-many" + tag); }',
    '    return { selection: valueKeys, canonical: valueKeys, value: valueKeys, valueLabel: labels.join(", "), valueKeys: valueKeys };',
    '  }',
    '  if (group.type === "text" || group.type === "long-text") {',
    '    var text = typeof raw === "string" ? raw.trim() : (typeof raw === "number" ? String(raw) : "");',
    '    if (text === "") { return null; }',
    '    var limit = group.type === "text" ? __poLimits.text : __poLimits.longText;',
    '    var maxLength = typeof group.maxLength === "number" ? Math.min(limit, group.maxLength) : limit;',
    '    if (text.length > maxLength) { errors.push("text-too-long" + tag); }',
    '    return { selection: text, canonical: text, value: text, valueLabel: text };',
    '  }',
    '  if (group.type === "number") {',
    '    if (typeof raw === "string" && raw.trim() === "") { return null; }',
    '    var number = __poFinite(raw);',
    '    if (number === undefined) { errors.push("not-a-number" + tag); return null; }',
    '    if ((typeof group.min === "number" && number < group.min) || (typeof group.max === "number" && number > group.max)) { errors.push("out-of-range" + tag); }',
    '    else if (__poOffStep(group.step, group.min, number)) { errors.push("off-step" + tag); }',
    '    var unit = __poText(group.unit);',
    '    return { selection: number, canonical: number, value: number, valueLabel: unit ? number + " " + unit : String(number), number: number };',
    '  }',
    '  if (group.type === "toggle") {',
    '    if (!__poFlag(raw)) { return null; }',
    '    return { selection: true, canonical: true, value: true, valueLabel: "Yes" };',
    '  }',
    // An upload is a safe ref of a type the group accepts (unknown accept reads as any; never SVG), at most uploadBytes.
    '  if (group.type === "upload") {',
    '    var items = Array.isArray(raw) ? raw : [raw];',
    '    var files = [];',
    '    var allowed = __poUploadMime[__poAccepts.indexOf(group.accept) !== -1 ? group.accept : "any"];',
    '    for (i = 0; i < items.length; i++) {',
    '      if (__poIsFileRef(items[i]) && allowed.indexOf(items[i].mimeType.trim().toLowerCase()) !== -1 && items[i].size <= __poLimits.uploadBytes) { files.push(items[i]); }',
    '      else if (!(typeof items[i] === "string" && items[i].trim() === "")) { if (errors.indexOf("bad-file" + tag) === -1) { errors.push("bad-file" + tag); } }',
    '    }',
    '    if (files.length === 0) { return null; }',
    '    if (files.length > 1) { errors.push("too-many-files" + tag); }',
    '    var ids = [];',
    '    var names = [];',
    '    var refs = [];',
    '    for (i = 0; i < files.length; i++) {',
    '      ids.push(files[i].id);',
    '      names.push(files[i].name || files[i].id);',
    '      refs.push({ id: files[i].id, name: files[i].name, size: files[i].size, url: files[i].url, mimeType: files[i].mimeType });',
    '    }',
    '    return { selection: ids, canonical: refs, value: ids, valueLabel: names.join(", "), files: files };',
    '  }',
    '  return null;',
    '}',
    'function __poPriceAnswer(group, read, base, selection, visibleKeys) {',
    '  if (group.type === "choice" || group.type === "multi-choice") {',
    '    var sum = 0;',
    '    var values = Array.isArray(group.values) ? group.values : [];',
    '    var keys = read.valueKeys || [];',
    '    for (var i = 0; i < keys.length; i++) {',
    '      for (var j = 0; j < values.length; j++) {',
    '        if (__poIsObject(values[j]) && values[j].key === keys[i]) { sum += __poRuleDelta(__poEffectiveRule(values[j], selection, visibleKeys), base, 1); break; }',
    '      }',
    '    }',
    '    return __poRound2(sum);',
    '  }',
    '  var quantity = group.type === "number" ? __poSafe(read.number) : 1;',
    '  return __poRuleDelta(__poEffectiveRule(group, selection, visibleKeys), base, quantity);',
    '}',
    // Labels: the short one-line label (values clipped to 80, whole <= 500) and the full details lines.
    'function __poLabel(entries) {',
    '  var list = Array.isArray(entries) ? entries : [];',
    '  var parts = [];',
    '  for (var i = 0; i < list.length; i++) {',
    '    if (!__poIsObject(list[i])) { continue; }',
    '    var name = __poOneLine(__poText(list[i].label));',
    '    var value = __poClip(__poOneLine(__poText(list[i].valueLabel)), 80, true);',
    '    parts.push(name ? name + ": " + value : value);',
    '  }',
    '  return __poClip(parts.join(" · "), __poLimits.configurationLabelChars, true);',
    '}',
    'function __poDetails(entries) {',
    '  var list = Array.isArray(entries) ? entries : [];',
    '  var lines = [];',
    '  for (var i = 0; i < list.length; i++) {',
    '    if (!__poIsObject(list[i])) { continue; }',
    '    var name = __poText(list[i].label);',
    '    var value = __poText(list[i].valueLabel);',
    '    lines.push(name ? name + ": " + value : value);',
    '  }',
    '  return lines.join(String.fromCharCode(10));',
    '}',
    // Also takes formatPriceRuleLabel's shape: __poPriceLabel(rule, {symbol, position, taxRate, unit}).
    'function __poPriceLabel(rule, symbol, position, taxRate, unit) {',
    '  if (__poIsObject(symbol)) { position = symbol.position; taxRate = symbol.taxRate; unit = symbol.unit; symbol = symbol.symbol; }',
    '  if (!rule || typeof rule !== "object") { return ""; }',
    '  if (rule.mode === "percent") {',
    '    var percent = Math.min(1000, Math.max(0, __poSafe(rule.percent)));',
    '    return percent > 0 ? "+" + __poRound2(percent) + "%" : "";',
    '  }',
    '  if (rule.mode !== "fixed" && rule.mode !== "per-unit") { return ""; }',
    '  var amount = Math.max(0, __poSafe(rule.amount));',
    '  if (amount <= 0) { return ""; }',
    '  var rate = __poSafe(taxRate);',
    '  var gross = rate > 0 ? __poRound2(amount * (1 + rate / 100)) : __poRound2(amount);',
    '  var fixed = gross.toFixed(2);',
    '  var money = position === "after" ? fixed + " " + (symbol || "") : (symbol || "") + fixed;',
    '  if (rule.mode === "fixed") { return "+" + money; }',
    '  return unit ? "+" + money + " / " + unit : "+" + money + " each";',
    '}',
    // Resolving: ONE forward pass. Hidden groups are dropped, each entry priced by its effective rule, the sum rounded once more.
    // An entry over maxAmount (or NaN / Infinity) is out-of-range and charges 0. pricesDisabled is true or {pricesDisabled: true}.
    'function __poResolve(base, groups, configuration, pricesDisabled) {',
    '  var disabled = pricesDisabled === true || (__poIsObject(pricesDisabled) && pricesDisabled.pricesDisabled === true);',
    '  var charged = __poSafe(base);',
    '  var list = [];',
    '  var i;',
    '  var j;',
    '  if (Array.isArray(groups)) { for (i = 0; i < groups.length; i++) { if (__poIsObject(groups[i])) { list.push(groups[i]); } } }',
    '  var answers = __poParseEntries(configuration);',
    '  var errors = [];',
    '  var missingKeys = [];',
    '  var missingLabels = [];',
    '  var visibleKeys = [];',
    '  var selection = {};',
    '  var entries = [];',
    '  var canonicalEntries = [];',
    '  var total = 0;',
    '  for (i = 0; i < answers.length; i++) {',
    '    var known = false;',
    '    for (j = 0; j < list.length; j++) { if (list[j].key === answers[i].key) { known = true; break; } }',
    '    if (!known) { errors.push("unknown-option:" + answers[i].key); }',
    '  }',
    '  for (i = 0; i < list.length; i++) {',
    '    var group = list[i];',
    '    if (!__poIsVisible(group, selection, visibleKeys)) { continue; }',
    '    visibleKeys.push(group.key);',
    '    var raw = undefined;',
    '    for (j = 0; j < answers.length; j++) { if (answers[j].key === group.key) { raw = answers[j].value; break; } }',
    '    var read = __poReadAnswer(group, raw, errors);',
    '    if (read === null) {',
    '      if (group.required) { missingKeys.push(group.key); missingLabels.push(__poText(group.label) || "Option " + (i + 1)); }',
    '      continue;',
    '    }',
    '    var priceDelta = disabled ? 0 : __poPriceAnswer(group, read, charged, selection, visibleKeys);',
    '    if (!(priceDelta <= __poLimits.maxAmount)) {',
    '      if (errors.indexOf("out-of-range:" + group.key) === -1) { errors.push("out-of-range:" + group.key); }',
    '      priceDelta = 0;',
    '    }',
    '    total += priceDelta;',
    '    selection[group.key] = read.selection;',
    '    canonicalEntries.push({ key: group.key, value: read.canonical });',
    '    var entry = { key: group.key, label: __poText(group.label), type: group.type, value: read.value, valueLabel: read.valueLabel, priceDelta: priceDelta };',
    '    if (read.files) { entry.files = read.files; }',
    '    entries.push(entry);',
    '  }',
    '  var canonical = __poCanonical(canonicalEntries);',
    '  if (canonical.length > __poLimits.configurationChars) { errors.push("too-long"); }',
    '  return { delta: disabled ? 0 : __poRound2(total), entries: entries, canonical: canonical, key: __poKey(canonicalEntries), label: __poLabel(entries), details: __poDetails(entries), valid: errors.length === 0 && missingKeys.length === 0, errors: errors, missingKeys: missingKeys, missingLabels: missingLabels, visibleKeys: visibleKeys };',
    '}',
    // A product row: gift cards and recurring products never charge for options.
    'function __poResolveForRow(row, base, configuration) {',
    '  var source = __poIsObject(row) ? row : {};',
    '  var disabled = __poFlag(source.is_gift_card) || __poText(source.payment_type).trim().toLowerCase() === "recurring";',
    '  return __poResolve(base, __poParseGroups(source.option_groups), configuration, disabled);',
    '}',
    'function __poRequiresInput(groups) {',
    '  return !__poResolve(0, groups, __poDefaultEntries(groups), false).valid;',
    '}',
    'function __poQuickAdd(groups, base, pricesDisabled) {',
    '  var resolved = __poResolve(base, groups, __poDefaultEntries(groups), pricesDisabled);',
    '  return resolved.valid && resolved.delta === 0;',
    '}',
    // Localizing: structure and prices from input.main, label / help / placeholder / value strings from input.clone by key.
    // Also takes localizeProductOptionGroups' shape: __poLocalize(main, clone), main being a list or its JSON.
    'function __poCopyObject(source) {',
    '  var out = {};',
    '  for (var k in source) { if (Object.prototype.hasOwnProperty.call(source, k)) { out[k] = source[k]; } }',
    '  return out;',
    '}',
    'function __poLocalize(input) {',
    '  var source = __poIsObject(input) ? input : { main: input, clone: arguments[1] };',
    '  var groups = __poParseGroups(source.main);',
    '  var clones = __poParseGroups(source.clone);',
    '  if (clones.length === 0) { return groups; }',
    '  var out = [];',
    '  for (var i = 0; i < groups.length; i++) {',
    '    var group = groups[i];',
    '    var translated = __poFindGroup(clones, group.key, null);',
    '    if (!translated) { out.push(group); continue; }',
    '    var next = __poCopyObject(group);',
    '    next.label = translated.label || group.label;',
    '    if (group.helpText && translated.helpText) { next.helpText = translated.helpText; }',
    '    if (group.placeholder && translated.placeholder) { next.placeholder = translated.placeholder; }',
    '    if (Array.isArray(group.values)) {',
    '      var translatedValues = Array.isArray(translated.values) ? translated.values : [];',
    '      var values = [];',
    '      for (var j = 0; j < group.values.length; j++) {',
    '        var value = group.values[j];',
    '        var match = null;',
    '        for (var k = 0; k < translatedValues.length; k++) { if (translatedValues[k].key === value.key) { match = translatedValues[k]; break; } }',
    '        if (!match) { values.push(value); continue; }',
    '        var localized = __poCopyObject(value);',
    '        localized.label = match.label || value.label;',
    '        if (value.description && match.description) { localized.description = match.description; }',
    '        values.push(localized);',
    '      }',
    '      next.values = values;',
    '    }',
    '    out.push(next);',
    '  }',
    '  return out;',
    '}',
    // Order-line snapshots: v1 {v, basePrice, priceDelta, entries} or the legacy compact [{key, value}].
    'function __poNullable(v) {',
    '  var parsed = __poFinite(v);',
    '  return parsed === undefined ? null : parsed;',
    '}',
    'function __poSafeFiles(raw) {',
    '  var list = Array.isArray(raw) ? raw : [];',
    '  var out = [];',
    '  for (var i = 0; i < list.length; i++) {',
    '    if (__poIsFileRef(list[i])) { out.push({ id: list[i].id, name: list[i].name, size: list[i].size, url: list[i].url, mimeType: list[i].mimeType }); }',
    '  }',
    '  return out;',
    '}',
    'function __poFileNames(files) {',
    '  var names = [];',
    '  for (var i = 0; i < files.length; i++) { names.push(files[i].name || files[i].id); }',
    '  return names.join(", ");',
    '}',
    'function __poDescribeValue(value) {',
    '  if (Array.isArray(value)) { return value.join(", "); }',
    '  if (typeof value === "boolean") { return value ? "Yes" : "No"; }',
    '  return String(value);',
    '}',
    'function __poSnapshotValue(value) {',
    '  if (typeof value === "string" || typeof value === "boolean") { return value; }',
    '  if (typeof value === "number") { return isFinite(value) ? value : ""; }',
    '  if (Array.isArray(value)) {',
    '    var out = [];',
    '    for (var i = 0; i < value.length; i++) {',
    '      if (typeof value[i] === "string" || (typeof value[i] === "number" && isFinite(value[i]))) { out.push(__poText(value[i])); }',
    '    }',
    '    return out;',
    '  }',
    '  return "";',
    '}',
    'function __poParseSnapshot(raw) {',
    '  var source = raw;',
    '  if (typeof source === "string") {',
    '    var trimmed = source.trim();',
    '    if (trimmed === "") { return null; }',
    '    try { source = JSON.parse(trimmed); } catch (e) { return null; }',
    '  }',
    '  var entries = [];',
    '  var i;',
    '  if (__poIsObject(source) && (source.v === 1 || source.v === "1")) {',
    '    var list = Array.isArray(source.entries) ? source.entries : [];',
    '    for (i = 0; i < list.length; i++) {',
    '      var item = list[i];',
    '      if (!__poIsObject(item)) { continue; }',
    '      var key = __poText(item.key).trim();',
    '      if (key === "") { continue; }',
    '      var files = __poSafeFiles(item.files);',
    '      var value = __poSnapshotValue(item.value);',
    '      entries.push({ key: key, label: __poText(item.label) || key, type: __poText(item.type), value: value, valueLabel: __poText(item.valueLabel) || (files.length > 0 ? __poFileNames(files) : __poDescribeValue(value)), priceDelta: __poNullable(item.priceDelta), files: files });',
    '    }',
    '    return { version: 1, basePrice: __poNullable(source.basePrice), priceDelta: __poNullable(source.priceDelta), entries: entries };',
    '  }',
    '  if (Array.isArray(source)) {',
    '    var parsed = __poParseEntries(source);',
    '    for (i = 0; i < parsed.length; i++) {',
    '      var legacy = parsed[i].value;',
    '      if (Array.isArray(legacy) && legacy.length > 0 && typeof legacy[0] === "object") {',
    '        var safe = __poSafeFiles(legacy);',
    '        var ids = [];',
    '        for (var j = 0; j < safe.length; j++) { ids.push(safe[j].id); }',
    '        entries.push({ key: parsed[i].key, label: parsed[i].key, type: "", value: ids, valueLabel: safe.length > 0 ? __poFileNames(safe) : __poDescribeValue(ids), priceDelta: null, files: safe });',
    '      } else {',
    '        entries.push({ key: parsed[i].key, label: parsed[i].key, type: "", value: legacy, valueLabel: __poDescribeValue(legacy), priceDelta: null, files: [] });',
    '      }',
    '    }',
    '    return { version: 0, basePrice: null, priceDelta: null, entries: entries };',
    '  }',
    '  return null;',
    '}',
    // Validating: the same issues, in the same order, as validateProductOptionsForProduct.
    'function __poOptionName(label, index, prefix) {',
    '  return __poText(label).trim() || prefix + (index + 1);',
    '}',
    'function __poMessage(code, option, source) {',
    '  return __poMessages[code].split("{option}").join(option).split("{source}").join(source);',
    '}',
    'function __poIssue(issues, code, target) {',
    '  issues.push({ severity: __poWarningCodes.indexOf(code) !== -1 ? "warning" : "error", code: code, message: __poMessage(code, target.option, target.source || ""), groupIndex: target.groupIndex, groupKey: target.groupKey, valueKey: target.valueKey });',
    '}',
    'function __poCheckRule(issues, rule, context) {',
    '  if (!__poIsObject(rule)) { return; }',
    '  if (rule.mode === "fixed" || rule.mode === "per-unit") {',
    '    var amount = __poFinite(rule.amount);',
    '    if (amount === undefined || amount < 0 || amount > __poLimits.maxAmount) { __poIssue(issues, "PRICE_AMOUNT_INVALID", context); }',
    '    if (rule.mode === "per-unit" && !context.allowPerUnit) { __poIssue(issues, "PRICE_PER_UNIT_NUMBER_ONLY", context); }',
    '  } else if (rule.mode === "percent") {',
    '    var percent = __poFinite(rule.percent);',
    '    if (percent === undefined || percent < 0 || percent > 1000) { __poIssue(issues, "PRICE_PERCENT_RANGE", context); }',
    '  }',
    '}',
    'function __poCheckSource(issues, rule, context) {',
    '  var codes = context.kind === "price"',
    '    ? ["PRICE_SOURCE_MISSING", "PRICE_SOURCE_LATER", "PRICE_SOURCE_TYPE", "PRICE_SOURCE_VALUES"]',
    '    : ["VISIBILITY_SOURCE_MISSING", "VISIBILITY_SOURCE_LATER", "VISIBILITY_SOURCE_TYPE", "VISIBILITY_SOURCE_VALUES"];',
    '  var sourceIndex = -1;',
    '  for (var i = 0; i < context.groups.length; i++) {',
    '    if (__poIsObject(context.groups[i]) && context.groups[i].key === rule.groupKey) { sourceIndex = i; break; }',
    '  }',
    '  if (sourceIndex === -1) { __poIssue(issues, codes[0], context); return; }',
    '  var source = context.groups[sourceIndex];',
    '  var named = __poWith(context, "source", __poOptionName(source.label, sourceIndex, "Option "));',
    '  if (sourceIndex >= context.groupIndex) { __poIssue(issues, codes[1], named); return; }',
    '  if (__poSelectableTypes.indexOf(source.type) === -1) { __poIssue(issues, codes[2], named); return; }',
    '  if (!context.needsValues) { return; }',
    '  var listed = Array.isArray(rule.valueKeys) ? rule.valueKeys : [];',
    '  var allowed = __poSourceValueKeys(source);',
    '  var bad = listed.length === 0;',
    '  for (var j = 0; j < listed.length; j++) { if (allowed.indexOf(listed[j]) === -1) { bad = true; } }',
    '  if (bad) { __poIssue(issues, codes[3], named); }',
    '}',
    'function __poCheckOverrides(issues, overrides, context) {',
    '  if (!Array.isArray(overrides)) { return; }',
    '  if (overrides.length > __poLimits.priceOverrides) { __poIssue(issues, "PRICE_TOO_MANY_OVERRIDES", context); }',
    '  for (var i = 0; i < overrides.length; i++) {',
    '    var override = overrides[i];',
    '    if (!__poIsObject(override)) { continue; }',
    '    __poCheckSource(issues, override, __poWith(__poWith(context, "kind", "price"), "needsValues", true));',
    '    __poCheckRule(issues, override.price, context);',
    '  }',
    '}',
    'function __poCheckValues(issues, group, context) {',
    '  var values = Array.isArray(group.values) ? group.values : [];',
    '  if (values.length === 0) { __poIssue(issues, "CHOICE_NEEDS_VALUE", context); }',
    '  if (values.length > __poLimits.values) { __poIssue(issues, "TOO_MANY_VALUES", context); }',
    '  var seen = [];',
    '  var seenLabels = [];',
    '  var labelMissing = false;',
    '  var labelTooLong = false;',
    '  var labelRepeated = false;',
    '  var defaults = 0;',
    '  for (var i = 0; i < values.length; i++) {',
    '    var value = values[i];',
    '    if (!__poIsObject(value)) { continue; }',
    '    if (value["default"] === true) { defaults += 1; }',
    '    var valueContext = __poWith(context, "valueKey", value.key);',
    '    var label = __poText(value.label).trim();',
    '    if (label === "" && !labelMissing) { __poIssue(issues, "VALUE_LABEL_REQUIRED", valueContext); labelMissing = true; }',
    '    else if (label.length > __poLimits.labelChars && !labelTooLong) { __poIssue(issues, "VALUE_LABEL_TOO_LONG", valueContext); labelTooLong = true; }',
    '    var labelKey = label.toLowerCase();',
    '    if (label !== "" && seenLabels.indexOf(labelKey) !== -1 && !labelRepeated) { __poIssue(issues, "VALUE_LABEL_DUPLICATE", valueContext); labelRepeated = true; }',
    '    if (label !== "") { seenLabels.push(labelKey); }',
    '    if (seen.indexOf(value.key) !== -1) { __poIssue(issues, "DUPLICATE_VALUE_KEY", valueContext); }',
    '    seen.push(value.key);',
    '    __poCheckRule(issues, value.price, valueContext);',
    '    __poCheckOverrides(issues, value.priceWhen, valueContext);',
    '  }',
    // A required pick-several needs one pick even without a minimum, as the resolver reads it.
    '  if (group.type === "multi-choice" && values.length > 0) {',
    '    var min = Math.max(group.required ? 1 : 0, typeof group.minSelected === "number" ? group.minSelected : 0);',
    '    var max = typeof group.maxSelected === "number" ? group.maxSelected : values.length;',
    '    if (max < 1) { __poIssue(issues, "MULTI_MAX_TOO_LOW", context); }',
    '    else if (min > max) { __poIssue(issues, "MULTI_MIN_MAX", context); }',
    '    else if (min > values.length || max > values.length) { __poIssue(issues, "MULTI_TOO_FEW_VALUES", context); }',
    // The page would open on these defaults, which the resolver refuses as too many.
    '    else if (defaults > max) { __poIssue(issues, "MULTI_DEFAULTS_TOO_MANY", context); }',
    '  }',
    '}',
    'function __poCheckNumber(issues, group, target) {',
    '  var min = typeof group.min === "number" ? group.min : null;',
    '  var max = typeof group.max === "number" ? group.max : null;',
    '  if (min !== null && max !== null && min > max) { __poIssue(issues, "NUMBER_MIN_MAX", target); }',
    '  if (group.step !== undefined && group.step !== null && !(__poSafe(group.step) > 0)) { __poIssue(issues, "NUMBER_STEP", target); }',
    '  var start = typeof group.defaultValue === "number" ? group.defaultValue : null;',
    '  if (start !== null && ((min !== null && start < min) || (max !== null && start > max))) { __poIssue(issues, "NUMBER_DEFAULT_RANGE", target); }',
    '  else if (start !== null && __poOffStep(group.step, group.min, start)) { __poIssue(issues, "NUMBER_DEFAULT_STEP", target); }',
    '}',
    // The longest canonical string: text at 2 per character (escapes), an upload at the longest safe ref (2862), a number at 24.
    'function __poWorstCase(groups) {',
    '  var list = Array.isArray(groups) ? groups : [];',
    '  var total = 2;',
    '  var count = 0;',
    '  for (var i = 0; i < list.length; i++) {',
    '    var group = list[i];',
    '    if (!__poIsObject(group)) { continue; }',
    '    var values = Array.isArray(group.values) ? group.values : [];',
    '    var answer = 0;',
    '    var j;',
    '    if (group.type === "choice") {',
    '      answer = 2;',
    '      for (j = 0; j < values.length; j++) { answer = Math.max(answer, __poText(values[j] && values[j].key).length + 2); }',
    '    } else if (group.type === "multi-choice") {',
    '      answer = 2 + Math.max(0, values.length - 1);',
    '      for (j = 0; j < values.length; j++) { answer += __poText(values[j] && values[j].key).length + 2; }',
    '    } else if (group.type === "text" || group.type === "long-text") {',
    '      var limit = group.type === "text" ? __poLimits.text : __poLimits.longText;',
    '      answer = (typeof group.maxLength === "number" ? Math.min(limit, group.maxLength) : limit) * 2 + 2;',
    '    } else if (group.type === "number") { answer = 24; }',
    '    else if (group.type === "toggle") { answer = 4; }',
    '    else if (group.type === "upload") { answer = 2862; }',
    '    total += 19 + __poText(group.key).length + answer;',
    '    count++;',
    '  }',
    '  return count > 1 ? total + count - 1 : total;',
    '}',
    'function __poRuleCharges(rule) {',
    '  if (!__poIsObject(rule)) { return false; }',
    '  if (rule.mode === "fixed" || rule.mode === "per-unit") { return __poSafe(rule.amount) > 0; }',
    '  return rule.mode === "percent" && __poSafe(rule.percent) > 0;',
    '}',
    'function __poTargetCharges(target) {',
    '  if (__poRuleCharges(target.price)) { return true; }',
    '  var overrides = Array.isArray(target.priceWhen) ? target.priceWhen : [];',
    '  for (var i = 0; i < overrides.length; i++) { if (__poIsObject(overrides[i]) && __poRuleCharges(overrides[i].price)) { return true; } }',
    '  return false;',
    '}',
    'function __poHasPrices(groups) {',
    '  var list = Array.isArray(groups) ? groups : [];',
    '  for (var i = 0; i < list.length; i++) {',
    '    if (!__poIsObject(list[i])) { continue; }',
    '    if (__poTargetCharges(list[i])) { return true; }',
    '    var values = Array.isArray(list[i].values) ? list[i].values : [];',
    '    for (var j = 0; j < values.length; j++) { if (__poIsObject(values[j]) && __poTargetCharges(values[j])) { return true; } }',
    '  }',
    '  return false;',
    '}',
    // Also takes validateProductOptionsForProduct's shape: __poValidate(groups, {isGiftCard, paymentType}).
    'function __poValidate(groups, isGiftCard, paymentType) {',
    '  if (__poIsObject(isGiftCard)) { paymentType = isGiftCard.paymentType; isGiftCard = isGiftCard.isGiftCard; }',
    '  var issues = [];',
    '  var list = Array.isArray(groups) ? groups : [];',
    '  var none = { groupIndex: null, groupKey: null, valueKey: null, option: "" };',
    '  if (list.length > __poLimits.groups) { __poIssue(issues, "TOO_MANY_GROUPS", none); }',
    '  var seenKeys = [];',
    '  for (var i = 0; i < list.length; i++) {',
    '    var group = list[i];',
    '    if (!__poIsObject(group)) { continue; }',
    '    var target = { groupIndex: i, groupKey: group.key, valueKey: null, option: __poOptionName(group.label, i, "Option ") };',
    '    var label = __poText(group.label).trim();',
    '    if (label === "") { __poIssue(issues, "GROUP_LABEL_REQUIRED", target); }',
    '    else if (label.length > __poLimits.labelChars) { __poIssue(issues, "GROUP_LABEL_TOO_LONG", target); }',
    '    if (seenKeys.indexOf(group.key) !== -1) { __poIssue(issues, "DUPLICATE_GROUP_KEY", target); }',
    '    seenKeys.push(group.key);',
    '    var context = __poWith(__poWith(target, "groups", list), "allowPerUnit", false);',
    '    if (__poValueTypes.indexOf(group.type) !== -1) { __poCheckValues(issues, group, context); }',
    '    if (group.type === "text" || group.type === "long-text") {',
    '      var limit = group.type === "text" ? __poLimits.text : __poLimits.longText;',
    '      var maxLength = group.maxLength;',
    '      if (maxLength !== undefined && maxLength !== null && (typeof maxLength !== "number" || Math.floor(maxLength) !== maxLength || maxLength < 1 || maxLength > limit)) {',
    '        __poIssue(issues, group.type === "text" ? "TEXT_MAX_LENGTH" : "LONG_TEXT_MAX_LENGTH", target);',
    '      }',
    '    }',
    '    if (group.type === "number") { __poCheckNumber(issues, group, target); }',
    '    if (__poPricedTypes.indexOf(group.type) !== -1) {',
    '      var priced = __poWith(context, "allowPerUnit", group.type === "number");',
    '      __poCheckRule(issues, group.price, priced);',
    '      __poCheckOverrides(issues, group.priceWhen, priced);',
    '    }',
    '    var rules = Array.isArray(group.visibleWhen) ? group.visibleWhen : [];',
    '    if (rules.length > __poLimits.rules) { __poIssue(issues, "VISIBILITY_TOO_MANY_RULES", target); }',
    '    for (var r = 0; r < rules.length; r++) {',
    '      if (__poIsObject(rules[r])) {',
    '        var needsValues = rules[r].operator === "is" || rules[r].operator === "is-not";',
    '        __poCheckSource(issues, rules[r], __poWith(__poWith(context, "kind", "visibility"), "needsValues", needsValues));',
    '      }',
    '    }',
    '  }',
    '  if (__poWorstCase(list) > __poLimits.configurationChars) { __poIssue(issues, "CONFIGURATION_TOO_LONG", none); }',
    '  var serialized = __poSerialize(list);',
    '  if (serialized !== null && serialized.length > __poLimits.optionGroupsChars) { __poIssue(issues, "OPTION_GROUPS_TOO_LARGE", none); }',
    '  var disabled = __poFlag(isGiftCard) || __poText(paymentType).trim().toLowerCase() === "recurring";',
    '  if (disabled && __poHasPrices(list)) { __poIssue(issues, __poFlag(isGiftCard) ? "GIFT_CARD_OPTIONS_PRICE" : "RECURRING_OPTIONS_PRICE", none); }',
    '  return issues;',
    '}',
    PRODUCT_OPTIONS_HELPERS_CLOSING,
  ].join('\n')
