// GENERATED from src/utils/rich-text-embeds.ts — do not edit by hand. Regenerate with
// UPDATE_EMBED_RUNTIME=1 npx jest packages/teleport-shared/__tests__/utils/rich-text-embeds-runtime-module.ts
// (see generateEmbedRuntimeModuleSource for why this is a string).
/* tslint:disable:no-invalid-template-strings -- the lines are JavaScript source */
export const EMBED_RUNTIME_MODULE_SOURCE = [
  '/**',
  ' * Code embeds inside rich-text content — the shape the editor writes and the',
  ' * page reads back. Generated from @teleporthq/teleport-shared; edit it there.',
  ' *',
  ' * An embed is stored inside the content HTML as a <figure class="tq-embed">.',
  ' * Passive markup (a provider iframe) lives in the figure as real children, so',
  ' * it renders server-side with no JavaScript. Markup that can execute — a',
  ' * <script>, an on* handler, a javascript: URL — is base64-encoded onto the',
  ' * element instead, and mounted at runtime inside a sandboxed iframe so it can',
  ' * never reach this page.',
  ' */',
  '',
  'export var EMBED_CLASS_NAME = "tq-embed"',
  '',
  'export var EMBED_FRAME_CLASS_NAME = "tq-embed-frame"',
  '',
  'export var EMBED_CAPTION_CLASS_NAME = "tq-embed-caption"',
  '',
  'export var EMBED_BLOT_NAME = "tq-embed"',
  '',
  'export var EMBED_ATTR = {',
  '  "MARKER": "data-tq-embed",',
  '  "PROVIDER": "data-tq-embed-provider",',
  '  "URL": "data-tq-embed-url",',
  '  "MODE": "data-tq-embed-mode",',
  '  "CODE": "data-tq-embed-code",',
  '  "RATIO": "data-tq-embed-ratio",',
  '  "WIDTH": "data-tq-embed-width",',
  '  "ALIGN": "data-tq-embed-align",',
  '  "CAPTION": "data-tq-embed-caption",',
  '  "SANDBOX": "data-tq-embed-sandbox",',
  '  "ACTIVATED": "data-tq-embed-activated",',
  '  "PREVIEW": "data-tq-embed-preview"',
  '}',
  '',
  'export var EMBED_ALIGNMENTS = ["center","float-left","float-right"]',
  '',
  'export var CUSTOM_EMBED_PROVIDER_ID = "custom"',
  '',
  'export var GENERIC_EMBED_PROVIDER_ID = "iframe-url"',
  '',
  'export var DEFAULT_EMBED_WIDTH = 100',
  '',
  'export var DEFAULT_EMBED_ALIGN = "center"',
  '',
  'export var DEFAULT_EMBED_SANDBOX_LEVEL = "strict"',
  '',
  'export var WIDESCREEN_EMBED_RATIO = 56.25',
  '',
  'export var EMBED_CAPTION_STYLE = "margin-top:8px;font-size:0.875em;line-height:1.5;opacity:0.75;text-align:center"',
  '',
  'export var EMBED_PROVIDERS = [',
  '  { id: "youtube", label: "YouTube", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.|m\\\\.)?youtube\\\\.com\\\\/watch\\\\?(?:[^#]*&)?v=([A-Za-z0-9_-]{6,})", "i"), new RegExp("^https?:\\\\/\\\\/youtu\\\\.be\\\\/([A-Za-z0-9_-]{6,})", "i"), new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?youtube\\\\.com\\\\/shorts\\\\/([A-Za-z0-9_-]{6,})", "i"), new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?youtube(?:-nocookie)?\\\\.com\\\\/embed\\\\/([A-Za-z0-9_-]{6,})", "i")], template: "<iframe src=\\"https://www.youtube.com/embed/$1\\" title=\\"YouTube video\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "vimeo", label: "Vimeo", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?vimeo\\\\.com\\\\/(\\\\d+)", "i"), new RegExp("^https?:\\\\/\\\\/player\\\\.vimeo\\\\.com\\\\/video\\\\/(\\\\d+)", "i")], template: "<iframe src=\\"https://player.vimeo.com/video/$1\\" title=\\"Vimeo video\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "loom", label: "Loom", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?loom\\\\.com\\\\/(?:share|embed)\\\\/([A-Za-z0-9]+)", "i")], template: "<iframe src=\\"https://www.loom.com/embed/$1\\" title=\\"Loom video\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "dailymotion", label: "Dailymotion", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?dailymotion\\\\.com\\\\/video\\\\/([A-Za-z0-9]+)", "i"), new RegExp("^https?:\\\\/\\\\/dai\\\\.ly\\\\/([A-Za-z0-9]+)", "i")], template: "<iframe src=\\"https://www.dailymotion.com/embed/video/$1\\" title=\\"Dailymotion video\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "spotify", label: "Spotify", patterns: [new RegExp("^https?:\\\\/\\\\/open\\\\.spotify\\\\.com\\\\/(?:embed\\\\/)?(track|album|playlist|episode|show|artist)\\\\/([A-Za-z0-9]+)", "i")], template: "<iframe src=\\"https://open.spotify.com/embed/$1/$2\\" title=\\"Spotify player\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:352px\\"></iframe>", ratio: null },',
  '  { id: "soundcloud", label: "SoundCloud", patterns: [new RegExp("^https?:\\\\/\\\\/soundcloud\\\\.com\\\\/[^?#]+", "i")], template: "<iframe src=\\"https://w.soundcloud.com/player/?url=$E&&color=%23ff5500&auto_play=false&show_teaser=false\\" title=\\"SoundCloud player\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:166px\\"></iframe>", ratio: null },',
  '  { id: "apple-podcasts", label: "Apple Podcasts", patterns: [new RegExp("^https?:\\\\/\\\\/podcasts\\\\.apple\\\\.com\\\\/(.+)$", "i")], template: "<iframe src=\\"https://embed.podcasts.apple.com/$1\\" title=\\"Apple Podcasts player\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:175px\\"></iframe>", ratio: null },',
  '  { id: "twitter", label: "X (Twitter)", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?(?:twitter|x)\\\\.com\\\\/[^/]+\\\\/status\\\\/(\\\\d+)", "i")], template: "<blockquote class=\\"twitter-tweet\\"><a href=\\"$&\\"></a></blockquote><script async src=\\"https://platform.twitter.com/widgets.js\\" charset=\\"utf-8\\"></script>", ratio: null },',
  '  { id: "instagram", label: "Instagram", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?instagram\\\\.com\\\\/(?:p|reel|tv)\\\\/([A-Za-z0-9_-]+)", "i")], template: "<blockquote class=\\"instagram-media\\" data-instgrm-permalink=\\"https://www.instagram.com/p/$1/\\" data-instgrm-version=\\"14\\"></blockquote><script async src=\\"https://www.instagram.com/embed.js\\"></script>", ratio: null },',
  '  { id: "tiktok", label: "TikTok", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?tiktok\\\\.com\\\\/@[^/]+\\\\/video\\\\/(\\\\d+)", "i")], template: "<blockquote class=\\"tiktok-embed\\" cite=\\"$&\\" data-video-id=\\"$1\\"><section></section></blockquote><script async src=\\"https://www.tiktok.com/embed.js\\"></script>", ratio: null },',
  '  { id: "reddit", label: "Reddit", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?reddit\\\\.com\\\\/r\\\\/[^/]+\\\\/comments\\\\/.+", "i")], template: "<blockquote class=\\"reddit-embed-bq\\"><a href=\\"$&\\"></a></blockquote><script async src=\\"https://embed.reddit.com/widgets.js\\" charset=\\"UTF-8\\"></script>", ratio: null },',
  '  { id: "pinterest", label: "Pinterest", patterns: [new RegExp("^https?:\\\\/\\\\/(?:[a-z]{2}\\\\.)?pinterest\\\\.[a-z.]+\\\\/pin\\\\/[0-9]+", "i")], template: "<a data-pin-do=\\"embedPin\\" href=\\"$&\\"></a><script async defer src=\\"https://assets.pinterest.com/js/pinit.js\\"></script>", ratio: null },',
  '  { id: "facebook", label: "Facebook", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.|web\\\\.)?facebook\\\\.com\\\\/.+\\\\/(?:posts|videos)\\\\/.+", "i")], template: "<iframe src=\\"https://www.facebook.com/plugins/post.php?href=$E&&show_text=true\\" title=\\"Facebook post\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:500px\\"></iframe>", ratio: null },',
  '  { id: "github-gist", label: "GitHub Gist", patterns: [new RegExp("^https?:\\\\/\\\\/gist\\\\.github\\\\.com\\\\/([^/]+\\\\/[a-f0-9]+)", "i")], template: "<script src=\\"https://gist.github.com/$1.js\\"></script>", ratio: null },',
  '  { id: "codepen", label: "CodePen", patterns: [new RegExp("^https?:\\\\/\\\\/codepen\\\\.io\\\\/([^/]+)\\\\/(?:pen|embed|details|full)\\\\/([A-Za-z0-9]+)", "i")], template: "<iframe src=\\"https://codepen.io/$1/embed/$2?default-tab=result\\" title=\\"CodePen\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:400px\\"></iframe>", ratio: null },',
  '  { id: "codesandbox", label: "CodeSandbox", patterns: [new RegExp("^https?:\\\\/\\\\/codesandbox\\\\.io\\\\/(?:s|embed)\\\\/([A-Za-z0-9_-]+)", "i"), new RegExp("^https?:\\\\/\\\\/codesandbox\\\\.io\\\\/p\\\\/(?:sandbox|devbox)\\\\/([A-Za-z0-9_-]+)", "i")], template: "<iframe src=\\"https://codesandbox.io/embed/$1\\" title=\\"CodeSandbox\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:500px\\"></iframe>", ratio: null },',
  '  { id: "jsfiddle", label: "JSFiddle", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?jsfiddle\\\\.net\\\\/((?:[^/]+\\\\/)?[A-Za-z0-9]+)\\\\/?", "i")], template: "<iframe src=\\"https://jsfiddle.net/$1/embedded/\\" title=\\"JSFiddle\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:400px\\"></iframe>", ratio: null },',
  '  { id: "figma", label: "Figma", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?figma\\\\.com\\\\/(?:file|design|proto|board|slides)\\\\/.+", "i")], template: "<iframe src=\\"https://www.figma.com/embed?embed_host=share&url=$E&\\" title=\\"Figma\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "canva", label: "Canva", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?canva\\\\.com\\\\/design\\\\/([A-Za-z0-9_-]+)\\\\/([A-Za-z0-9_-]+)\\\\/(?:view|watch)", "i")], template: "<iframe src=\\"https://www.canva.com/design/$1/$2/view?embed\\" title=\\"Canva design\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "miro", label: "Miro", patterns: [new RegExp("^https?:\\\\/\\\\/miro\\\\.com\\\\/app\\\\/(?:board|live-embed)\\\\/([A-Za-z0-9_=-]+)", "i")], template: "<iframe src=\\"https://miro.com/app/live-embed/$1/\\" title=\\"Miro board\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "google-maps", label: "Google Maps", patterns: [new RegExp("^https?:\\\\/\\\\/(?:www\\\\.)?google\\\\.[a-z.]+\\\\/maps\\\\/embed\\\\?(.+)$", "i")], template: "<iframe src=\\"https://www.google.com/maps/embed?$1\\" title=\\"Google Maps\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "google-maps-place", label: "Google Maps", patterns: [new RegExp("^https?:\\\\/\\\\/(?:(?:www\\\\.)?google\\\\.[a-z.]+\\\\/maps|maps\\\\.app\\\\.goo\\\\.gl)\\\\/.+", "i")], template: "<iframe src=\\"https://maps.google.com/maps?q=$E&&output=embed\\" title=\\"Google Maps\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 },',
  '  { id: "google-forms", label: "Google Forms", patterns: [new RegExp("^https?:\\\\/\\\\/docs\\\\.google\\\\.com\\\\/forms\\\\/d\\\\/(?:e\\\\/)?([A-Za-z0-9_-]+)", "i")], template: "<iframe src=\\"https://docs.google.com/forms/d/e/$1/viewform?embedded=true\\" title=\\"Google Form\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:700px\\"></iframe>", ratio: null },',
  '  { id: "google-docs", label: "Google Docs", patterns: [new RegExp("^https?:\\\\/\\\\/docs\\\\.google\\\\.com\\\\/(document|spreadsheets|presentation)\\\\/d\\\\/([A-Za-z0-9_-]+)", "i")], template: "<iframe src=\\"https://docs.google.com/$1/d/$2/preview\\" title=\\"Google Docs\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:600px\\"></iframe>", ratio: null },',
  '  { id: "airtable", label: "Airtable", patterns: [new RegExp("^https?:\\\\/\\\\/airtable\\\\.com\\\\/(?:embed\\\\/)?(app[A-Za-z0-9/?=&_-]+)", "i")], template: "<iframe src=\\"https://airtable.com/embed/$1\\" title=\\"Airtable\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:533px\\"></iframe>", ratio: null },',
  '  { id: "typeform", label: "Typeform", patterns: [new RegExp("^https?:\\\\/\\\\/(?:[A-Za-z0-9-]+\\\\.)?typeform\\\\.com\\\\/to\\\\/([A-Za-z0-9]+)", "i")], template: "<iframe src=\\"https://form.typeform.com/to/$1\\" title=\\"Typeform\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:500px\\"></iframe>", ratio: null },',
  '  { id: "calendly", label: "Calendly", patterns: [new RegExp("^https?:\\\\/\\\\/calendly\\\\.com\\\\/(.+)$", "i")], template: "<iframe src=\\"https://calendly.com/$1\\" title=\\"Calendly\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"display:block;width:100%;border:0;border-radius:inherit;height:700px\\"></iframe>", ratio: null },',
  '  { id: "iframe-url", label: "Web page", patterns: [new RegExp("^https:\\\\/\\\\/[^\\\\s\\"\'<>]+$", "i")], template: "<iframe src=\\"$&\\" title=\\"Embedded page\\" loading=\\"lazy\\" frameborder=\\"0\\" referrerpolicy=\\"strict-origin-when-cross-origin\\" allow=\\"accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share\\" allowfullscreen style=\\"position:absolute;top:0;left:0;width:100%;height:100%;border:0;border-radius:inherit\\"></iframe>", ratio: 56.25 }',
  ']',
  '',
  'export var EMBED_SANDBOX_FLAGS_STRICT = "allow-scripts allow-popups allow-popups-to-escape-sandbox allow-forms allow-presentation"',
  '',
  'export var EMBED_SANDBOX_FLAGS_TRUSTED = "allow-scripts allow-popups allow-popups-to-escape-sandbox allow-forms allow-presentation allow-same-origin"',
  '',
  'export var EMBED_HEIGHT_MESSAGE_TYPE = "tq-embed-height"',
  '',
  'export var EMBED_TOKEN_PLACEHOLDER = "__TQ_EMBED_TOKEN__"',
  '',
  'export var EMBED_MIN_HEIGHT = 80',
  '',
  'export var EMBED_MAX_HEIGHT = 6000',
  '',
  'export var EMBED_INITIAL_HEIGHT = 320',
  '',
  'export var EMBED_SANDBOX_DOC_HEAD = "<!doctype html><html><head><meta charset=\\"utf-8\\"><meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1\\"><base target=\\"_blank\\"><style>html,body{margin:0;padding:0;background:transparent}img,iframe,video,blockquote{max-width:100%}</style><script>(function(){var token=\\"__TQ_EMBED_TOKEN__\\";var last=0;function report(){try{var doc=document.documentElement;var body=document.body;var height=Math.max(doc?doc.scrollHeight:0,doc?doc.offsetHeight:0,body?body.scrollHeight:0,body?body.offsetHeight:0);if(!height||height===last){return;}last=height;parent.postMessage({type:\\"tq-embed-height\\",token:token,height:height},\\"*\\");}catch(e){}}function watch(){report();if(typeof ResizeObserver===\\"function\\"&&document.documentElement){new ResizeObserver(report).observe(document.documentElement);}if(typeof MutationObserver===\\"function\\"&&document.body){new MutationObserver(report).observe(document.body,{childList:true,subtree:true,attributes:true});}var delays=[150,400,900,1800,3500];for(var i=0;i<delays.length;i++){setTimeout(report,delays[i]);}}if(document.readyState===\\"loading\\"){document.addEventListener(\\"DOMContentLoaded\\",watch);}else{watch();}window.addEventListener(\\"load\\",report);})();</script></head><body>"',
  '',
  'export var EMBED_SANDBOX_DOC_TAIL = "</body></html>"',
  '',
  'export var embedTokenCounter = 0',
  '',
  'export function isSafeEmbedUrl(url) {',
  "    return /^https?:\\/\\/[^\\s\"'<>]+$/i.test((url || '').trim());",
  '}',
  '',
  'export function resolveEmbedProvider(url) {',
  "    const trimmed = (url || '').trim();",
  '    if (!isSafeEmbedUrl(trimmed)) {',
  '        return null;',
  '    }',
  '    for (const provider of EMBED_PROVIDERS) {',
  '        for (const pattern of provider.patterns) {',
  '            const match = trimmed.match(pattern);',
  '            if (match) {',
  '                return { provider, match };',
  '            }',
  '        }',
  '    }',
  '    return null;',
  '}',
  '',
  'export function applyEmbedTemplate(template, match, url) {',
  '    return template.replace(/\\$(\\$|E?(?:[1-9]|&))/g, (_token, spec) => {',
  '        var _a;',
  "        if (spec === '$') {",
  "            return '$';",
  '        }',
  "        const encoded = spec.charAt(0) === 'E';",
  '        const key = encoded ? spec.slice(1) : spec;',
  "        const raw = key === '&' ? url : (_a = match[Number(key)]) !== null && _a !== void 0 ? _a : '';",
  '        return encoded ? encodeURIComponent(raw) : raw;',
  '    });',
  '}',
  '',
  'export function buildEmbedHtmlFromUrl(url) {',
  '    const resolved = resolveEmbedProvider(url);',
  '    if (!resolved) {',
  '        return null;',
  '    }',
  '    return {',
  '        provider: resolved.provider,',
  '        html: applyEmbedTemplate(resolved.provider.template, resolved.match, url.trim()),',
  '    };',
  '}',
  '',
  'export function resolveEmbedMode(html) {',
  "    const markup = html || '';",
  '    const executes = /<script[\\s/>]/i.test(markup) ||',
  '        /\\son[a-z]+\\s*=/i.test(markup) ||',
  '        /(?:href|src|action|formaction)\\s*=\\s*["\']?\\s*javascript:/i.test(markup);',
  "    return executes ? 'sandbox' : 'inline';",
  '}',
  '',
  'export function clampEmbedWidth(width) {',
  '    if (!isFinite(width)) {',
  '        return DEFAULT_EMBED_WIDTH;',
  '    }',
  '    return Math.max(10, Math.min(100, Math.round(width)));',
  '}',
  '',
  'export function normalizeEmbedAlign(align) {',
  '    return EMBED_ALIGNMENTS.indexOf(align) !== -1',
  '        ? align',
  '        : DEFAULT_EMBED_ALIGN;',
  '}',
  '',
  'export function escapeEmbedAttribute(value) {',
  "    return String(value !== null && value !== void 0 ? value : '')",
  "        .replace(/&/g, '&amp;')",
  "        .replace(/\"/g, '&quot;')",
  "        .replace(/</g, '&lt;')",
  "        .replace(/>/g, '&gt;');",
  '}',
  '',
  'export function escapeEmbedText(value) {',
  "    return String(value !== null && value !== void 0 ? value : '')",
  "        .replace(/&/g, '&amp;')",
  "        .replace(/</g, '&lt;')",
  "        .replace(/>/g, '&gt;');",
  '}',
  '',
  'export function encodeEmbedCode(code) {',
  '    const binary = encodeURIComponent(code).replace(/%([0-9A-F]{2})/gi, (_m, hex) => String.fromCharCode(parseInt(hex, 16)));',
  "    if (typeof btoa === 'function') {",
  '        return btoa(binary);',
  '    }',
  "    if (typeof Buffer !== 'undefined') {",
  "        return Buffer.from(binary, 'binary').toString('base64');",
  '    }',
  "    throw new Error('No base64 encoder available');",
  '}',
  '',
  'export function decodeEmbedCode(encoded) {',
  '    let binary;',
  "    if (typeof atob === 'function') {",
  '        binary = atob(encoded);',
  '    }',
  "    else if (typeof Buffer !== 'undefined') {",
  "        binary = Buffer.from(encoded, 'base64').toString('binary');",
  '    }',
  '    else {',
  "        throw new Error('No base64 decoder available');",
  '    }',
  "    let percent = '';",
  '    for (let index = 0; index < binary.length; index += 1) {',
  '        percent += `%${`00${binary.charCodeAt(index).toString(16)}`.slice(-2)}`;',
  '    }',
  '    return decodeURIComponent(percent);',
  '}',
  '',
  'export function createEmbedValue(params) {',
  '    var _a, _b, _c;',
  "    const code = params.code || '';",
  '    return {',
  '        provider: params.provider || CUSTOM_EMBED_PROVIDER_ID,',
  "        url: params.url || '',",
  '        code,',
  '        mode: resolveEmbedMode(code),',
  '        ratio: (_a = params.ratio) !== null && _a !== void 0 ? _a : null,',
  '        width: clampEmbedWidth((_b = params.width) !== null && _b !== void 0 ? _b : DEFAULT_EMBED_WIDTH),',
  '        align: normalizeEmbedAlign((_c = params.align) !== null && _c !== void 0 ? _c : DEFAULT_EMBED_ALIGN),',
  "        caption: params.caption || '',",
  "        sandboxLevel: params.sandboxLevel === 'trusted' ? 'trusted' : DEFAULT_EMBED_SANDBOX_LEVEL,",
  '    };',
  '}',
  '',
  'export function embedBlockStyle(value) {',
  '    const declarations = [',
  "        'position:relative',",
  '        `width:${clampEmbedWidth(value.width)}%`,',
  "        'max-width:100%',",
  "        'margin:16px 0',",
  '    ];',
  "    if (value.align === 'center') {",
  "        declarations.push('margin-left:auto', 'margin-right:auto');",
  '    }',
  "    else if (value.align === 'float-left') {",
  "        declarations.push('float:left', 'margin-right:16px', 'margin-bottom:8px');",
  '    }',
  "    else if (value.align === 'float-right') {",
  "        declarations.push('float:right', 'margin-left:16px', 'margin-bottom:8px');",
  '    }',
  "    return declarations.join(';');",
  '}',
  '',
  'export function embedFrameStyle(ratio) {',
  '    if (ratio === null || !isFinite(ratio) || ratio <= 0) {',
  "        return 'position:relative;width:100%';",
  '    }',
  '    return `position:relative;width:100%;padding-top:${ratio}%`;',
  '}',
  '',
  'export function buildEmbedElementHtml(value) {',
  '    const attrs = [',
  '        `class="${EMBED_CLASS_NAME}"`,',
  '        `${EMBED_ATTR.MARKER}="1"`,',
  '        `${EMBED_ATTR.PROVIDER}="${escapeEmbedAttribute(value.provider)}"`,',
  '        `${EMBED_ATTR.MODE}="${value.mode}"`,',
  '        `${EMBED_ATTR.WIDTH}="${clampEmbedWidth(value.width)}"`,',
  '        `${EMBED_ATTR.ALIGN}="${value.align}"`,',
  '        `${EMBED_ATTR.SANDBOX}="${value.sandboxLevel}"`,',
  '    ];',
  '    if (value.url) {',
  '        attrs.push(`${EMBED_ATTR.URL}="${escapeEmbedAttribute(value.url)}"`);',
  '    }',
  '    if (value.ratio !== null) {',
  '        attrs.push(`${EMBED_ATTR.RATIO}="${value.ratio}"`);',
  '    }',
  '    if (value.caption) {',
  '        attrs.push(`${EMBED_ATTR.CAPTION}="${escapeEmbedAttribute(value.caption)}"`);',
  '    }',
  "    if (value.mode === 'sandbox') {",
  '        attrs.push(`${EMBED_ATTR.CODE}="${escapeEmbedAttribute(encodeEmbedCode(value.code))}"`);',
  '    }',
  '    attrs.push(\'contenteditable="false"\');',
  '    attrs.push(`style="${embedBlockStyle(value)}"`);',
  '    const caption = value.caption',
  '        ? `<figcaption class="${EMBED_CAPTION_CLASS_NAME}" style="${EMBED_CAPTION_STYLE}">${escapeEmbedText(value.caption)}</figcaption>`',
  "        : '';",
  "    return (`<figure ${attrs.join(' ')}>` +",
  '        `<div class="${EMBED_FRAME_CLASS_NAME}" style="${embedFrameStyle(value.ratio)}">` +',
  '        `${buildEmbedFrameChildren(value)}</div>${caption}</figure>`);',
  '}',
  '',
  'export function buildEmbedFrameChildren(value) {',
  "    if (value.mode === 'inline') {",
  '        return value.code;',
  '    }',
  '    if (!value.url) {',
  "        return '';",
  '    }',
  '    return (`<noscript><a href="${escapeEmbedAttribute(value.url)}" rel="noopener noreferrer" ` +',
  '        `target="_blank">${escapeEmbedText(value.url)}</a></noscript>`);',
  '}',
  '',
  'export function findEmbedFrame(element) {',
  '    return element.querySelector(`.${EMBED_FRAME_CLASS_NAME}`);',
  '}',
  '',
  'export function readEmbedValueFromElement(element) {',
  "    const mode = element.getAttribute(EMBED_ATTR.MODE) === 'sandbox' ? 'sandbox' : 'inline';",
  '    const frame = findEmbedFrame(element);',
  '    const rawRatio = element.getAttribute(EMBED_ATTR.RATIO);',
  '    const parsedRatio = rawRatio === null ? NaN : parseFloat(rawRatio);',
  "    let code = '';",
  "    if (mode === 'sandbox') {",
  '        code = readEncodedEmbedCode(element);',
  '    }',
  '    else if (frame) {',
  '        code = frame.innerHTML;',
  '    }',
  '    return {',
  '        provider: element.getAttribute(EMBED_ATTR.PROVIDER) || CUSTOM_EMBED_PROVIDER_ID,',
  "        url: element.getAttribute(EMBED_ATTR.URL) || '',",
  '        code,',
  '        mode,',
  '        ratio: isFinite(parsedRatio) ? parsedRatio : null,',
  "        width: clampEmbedWidth(parseFloat(element.getAttribute(EMBED_ATTR.WIDTH) || '')),",
  "        align: normalizeEmbedAlign(element.getAttribute(EMBED_ATTR.ALIGN) || ''),",
  "        caption: element.getAttribute(EMBED_ATTR.CAPTION) || '',",
  "        sandboxLevel: element.getAttribute(EMBED_ATTR.SANDBOX) === 'trusted'",
  "            ? 'trusted'",
  '            : DEFAULT_EMBED_SANDBOX_LEVEL,',
  '    };',
  '}',
  '',
  'export function readEncodedEmbedCode(element) {',
  '    const encoded = element.getAttribute(EMBED_ATTR.CODE);',
  '    if (!encoded) {',
  "        return '';",
  '    }',
  '    try {',
  '        return decodeEmbedCode(encoded);',
  '    }',
  '    catch (_a) {',
  "        return '';",
  '    }',
  '}',
  '',
  'export function normalizeEmbedsForStorage(root) {',
  '    const previews = root.querySelectorAll(`[${EMBED_ATTR.PREVIEW}]`);',
  '    for (let index = previews.length - 1; index >= 0; index -= 1) {',
  '        const preview = previews[index];',
  '        if (preview.parentNode) {',
  '            preview.parentNode.removeChild(preview);',
  '        }',
  '    }',
  '    const blocks = root.querySelectorAll(`[${EMBED_ATTR.MARKER}]`);',
  '    for (let index = 0; index < blocks.length; index += 1) {',
  '        const block = blocks[index];',
  '        block.removeAttribute(EMBED_ATTR.ACTIVATED);',
  '        const frame = findEmbedFrame(block);',
  '        if (!frame) {',
  '            continue;',
  '        }',
  '        const value = readEmbedValueFromElement(block);',
  "        if (value.mode !== 'sandbox') {",
  '            continue;',
  '        }',
  '        frame.innerHTML = buildEmbedFrameChildren(value);',
  '    }',
  '}',
  '',
  'export function resolveEmbedSandboxFlags(level) {',
  "    return level === 'trusted' ? EMBED_SANDBOX_FLAGS_TRUSTED : EMBED_SANDBOX_FLAGS_STRICT;",
  '}',
  '',
  'export function buildEmbedSandboxDocument(code, token) {',
  '    return (EMBED_SANDBOX_DOC_HEAD.replace(EMBED_TOKEN_PLACEHOLDER, token) +',
  "        (code || '') +",
  '        EMBED_SANDBOX_DOC_TAIL);',
  '}',
  '',
  'export function parseEmbedHeightMessage(data) {',
  "    if (!data || typeof data !== 'object') {",
  '        return null;',
  '    }',
  '    const message = data;',
  "    if (message.type !== EMBED_HEIGHT_MESSAGE_TYPE || typeof message.token !== 'string') {",
  '        return null;',
  '    }',
  '    const height = Number(message.height);',
  '    if (!isFinite(height) || height <= 0) {',
  '        return null;',
  '    }',
  '    return {',
  '        token: message.token,',
  '        height: Math.min(Math.max(Math.round(height), EMBED_MIN_HEIGHT), EMBED_MAX_HEIGHT),',
  '    };',
  '}',
  '',
  'export function createEmbedToken() {',
  '    embedTokenCounter += 1;',
  '    return `tqe-${Date.now().toString(36)}-${embedTokenCounter.toString(36)}-${Math.random()',
  '        .toString(36)',
  '        .slice(2, 8)}`;',
  '}',
  '',
].join('\n')
