// GENERATED from src/utils/rich-text-content.ts — do not edit by hand. Regenerate with
// UPDATE_RICH_TEXT_CONTENT_RUNTIME=1 npx jest packages/teleport-shared/__tests__/utils/rich-text-content-runtime-module.ts
// (see generateRichTextContentRuntimeModuleSource for why this is a string).
/* tslint:disable:no-invalid-template-strings -- the lines are JavaScript source */
export const RICH_TEXT_CONTENT_RUNTIME_MODULE_SOURCE = [
  '/**',
  ' * Rich-text content: the stored form of a post body and the form the editor',
  ' * holds. Generated from @teleporthq/teleport-shared; edit it there.',
  ' *',
  ' * Stored HTML is plain: nested lists, tables with header rows, code blocks,',
  " * callouts. The editor gets lists as Quill's lines and every block Quill has",
  ' * no blot for wrapped in a protected block it treats as one unit, and writes',
  ' * stored HTML back through fromEditorHtml.',
  ' */',
  '',
  'export var PROTECTED_BLOCK_CLASS = "tq-protected"',
  '',
  'export var PROTECTED_BLOCK_ATTR = "data-tq-protected"',
  '',
  'export var PROTECTED_BLOCK_BLOT_NAME = "tq-protected-block"',
  '',
  'export var PROTECTED_BLOCK_KINDS = [',
  '  "table",',
  '  "code",',
  '  "callout",',
  '  "list",',
  '  "quote",',
  '  "html"',
  ']',
  '',
  'export var CALLOUT_CLASS = "tq-callout"',
  '',
  'export var CALLOUT_KIND_ATTR = "data-kind"',
  '',
  'export var CALLOUT_KINDS = [',
  '  "note",',
  '  "tip",',
  '  "important",',
  '  "warning",',
  '  "caution"',
  ']',
  '',
  'export var RICH_TEXT_EMBED_CLASS = "tq-embed"',
  '',
  'export var RICH_TEXT_IMAGE_CLASS = "ql-content-image"',
  '',
  'export var QUILL_LIST_ITEM_ATTR = "data-list"',
  '',
  'export var QUILL_INDENT_CLASS_PREFIX = "ql-indent-"',
  '',
  'export var RICH_TEXT_INLINE_TAGS = [',
  '  "A",',
  '  "ABBR",',
  '  "B",',
  '  "BR",',
  '  "CODE",',
  '  "DEL",',
  '  "EM",',
  '  "I",',
  '  "IMG",',
  '  "INS",',
  '  "KBD",',
  '  "MARK",',
  '  "S",',
  '  "SMALL",',
  '  "SPAN",',
  '  "STRIKE",',
  '  "STRONG",',
  '  "SUB",',
  '  "SUP",',
  '  "U"',
  ']',
  '',
  'export var RICH_TEXT_BLOCK_TAGS = [',
  '  "ARTICLE",',
  '  "ASIDE",',
  '  "BLOCKQUOTE",',
  '  "DD",',
  '  "DETAILS",',
  '  "DIV",',
  '  "DL",',
  '  "DT",',
  '  "FIGCAPTION",',
  '  "FIGURE",',
  '  "FOOTER",',
  '  "FORM",',
  '  "H1",',
  '  "H2",',
  '  "H3",',
  '  "H4",',
  '  "H5",',
  '  "H6",',
  '  "HEADER",',
  '  "HR",',
  '  "LI",',
  '  "MAIN",',
  '  "NAV",',
  '  "OL",',
  '  "P",',
  '  "PRE",',
  '  "SECTION",',
  '  "SUMMARY",',
  '  "TABLE",',
  '  "TBODY",',
  '  "TD",',
  '  "TFOOT",',
  '  "TH",',
  '  "THEAD",',
  '  "TR",',
  '  "UL"',
  ']',
  '',
  'export function parseRichTextFragment(html) {',
  "    const doc = new DOMParser().parseFromString('<!doctype html><html><body>' + html, 'text/html');",
  '    return doc.body;',
  '}',
  '',
  'export function escapeRichTextText(value) {',
  "    return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');",
  '}',
  '',
  'export function escapeRichTextAttribute(value) {',
  "    return escapeRichTextText(value).replace(/\"/g, '&quot;');",
  '}',
  '',
  'export function isProtectedBlockKind(value) {',
  '    return PROTECTED_BLOCK_KINDS.indexOf(String(value)) !== -1;',
  '}',
  '',
  'export function buildProtectedBlockHtml(kind, html) {',
  '    return (`<div class="${PROTECTED_BLOCK_CLASS}" ${PROTECTED_BLOCK_ATTR}="${kind}" contenteditable="false">` +',
  '        html +',
  "        '</div>');",
  '}',
  '',
  'export function readProtectedBlockValue(element) {',
  '    const kind = element.getAttribute(PROTECTED_BLOCK_ATTR);',
  '    return {',
  "        kind: isProtectedBlockKind(kind) ? kind : 'html',",
  '        html: element.innerHTML,',
  '    };',
  '}',
  '',
  'export function isCalloutKind(value) {',
  '    return CALLOUT_KINDS.indexOf(String(value)) !== -1;',
  '}',
  '',
  'export function buildCalloutHtml(kind, innerHtml) {',
  '    return `<aside class="${CALLOUT_CLASS}" ${CALLOUT_KIND_ATTR}="${kind}">${innerHtml}</aside>`;',
  '}',
  '',
  'export function buildCodeBlockHtml(language, code, escaped) {',
  "    const text = escaped ? code : escapeRichTextText(code || '');",
  "    const lang = String(language || '').replace(/[^\\w.+#-]/g, '');",
  "    const classAttr = lang && lang !== 'plain' ? ` class=\"language-${lang}\"` : '';",
  '    return `<pre><code${classAttr}>${text}</code></pre>`;',
  '}',
  '',
  'export function hasClass(element, className) {',
  "    const classes = (element.getAttribute('class') || '').split(/\\s+/);",
  '    return classes.indexOf(className) !== -1;',
  '}',
  '',
  'export function isRichTextInlineNode(node) {',
  '    if (node.nodeType === 3 || node.nodeType === 8) {',
  '        return true;',
  '    }',
  '    if (node.nodeType !== 1) {',
  '        return false;',
  '    }',
  '    return RICH_TEXT_INLINE_TAGS.indexOf(node.tagName) !== -1;',
  '}',
  '',
  'export function isBlankTextNode(node) {',
  "    return node.nodeType === 3 && !/\\S/.test(node.nodeValue || '');",
  '}',
  '',
  'export function isRichTextBlockElement(node) {',
  '    return (!!node && node.nodeType === 1 && RICH_TEXT_BLOCK_TAGS.indexOf(node.tagName) !== -1);',
  '}',
  '',
  'export function stripInterBlockWhitespace(root) {',
  "    if (root.nodeType === 1 && root.tagName === 'PRE') {",
  '        return;',
  '    }',
  '    const rootIsBlock = root.nodeType !== 1 || isRichTextBlockElement(root);',
  '    const children = Array.prototype.slice.call(root.childNodes);',
  '    children.forEach((child) => {',
  '        if (child.nodeType === 3) {',
  '            const afterBlock = isRichTextBlockElement(child.previousSibling) || (rootIsBlock && !child.previousSibling);',
  '            const beforeBlock = isRichTextBlockElement(child.nextSibling) || (rootIsBlock && !child.nextSibling);',
  '            // A run of white space renders as one space; stored HTML keeps it that way',
  '            // (a no-break space is not white space here).',
  "            let text = (child.nodeValue || '').replace(/[ \\t\\r\\n\\f]+/g, ' ');",
  '            if (afterBlock) {',
  "                text = text.replace(/^\\s+/, '');",
  '            }',
  '            if (beforeBlock) {',
  "                text = text.replace(/\\s+$/, '');",
  '            }',
  '            if (!text && (afterBlock || beforeBlock)) {',
  '                root.removeChild(child);',
  '            }',
  '            else if (text !== child.nodeValue) {',
  '                child.nodeValue = text;',
  '            }',
  '            return;',
  '        }',
  '        if (child.nodeType === 1) {',
  '            stripInterBlockWhitespace(child);',
  '        }',
  '    });',
  '}',
  '',
  'export function unwrapSingleParagraphListItems(root) {',
  "    Array.prototype.slice.call(root.querySelectorAll('li')).forEach((item) => {",
  '        const paragraphs = Array.prototype.slice',
  '            .call(item.children)',
  "            .filter((child) => child.tagName === 'P');",
  '        const blocks = Array.prototype.slice',
  '            .call(item.children)',
  '            .filter((child) => !isRichTextInlineNode(child));',
  "        const nested = blocks.filter((child) => child.tagName === 'UL' || child.tagName === 'OL');",
  '        if (paragraphs.length !== 1 || blocks.length !== 1 + nested.length) {',
  '            return;',
  '        }',
  '        const paragraph = paragraphs[0];',
  '        while (paragraph.firstChild) {',
  '            item.insertBefore(paragraph.firstChild, paragraph);',
  '        }',
  '        item.removeChild(paragraph);',
  '    });',
  '}',
  '',
  'export function isExternalWebLink(href) {',
  "    return /^https?:\\/\\//i.test(String(href || '').trim());",
  '}',
  '',
  'export function normalizeLinkTargets(root) {',
  "    Array.prototype.slice.call(root.querySelectorAll('a[href]')).forEach((link) => {",
  "        if (isExternalWebLink(link.getAttribute('href') || '')) {",
  "            if (!link.getAttribute('target')) {",
  "                link.setAttribute('rel', 'noopener noreferrer');",
  "                link.setAttribute('target', '_blank');",
  '            }',
  '            return;',
  '        }',
  "        link.removeAttribute('target');",
  "        link.removeAttribute('rel');",
  '    });',
  '}',
  '',
  'export function wrapBareBlockquoteContent(root) {',
  "    Array.prototype.slice.call(root.querySelectorAll('blockquote')).forEach((quote) => {",
  '        const children = Array.prototype.slice.call(quote.childNodes);',
  '        const bare = children.filter((child) => !isBlankTextNode(child));',
  '        if (!bare.length || !bare.every((child) => isRichTextInlineNode(child))) {',
  '            return;',
  '        }',
  "        const paragraph = quote.ownerDocument.createElement('p');",
  '        children.forEach((child) => paragraph.appendChild(child));',
  '        quote.appendChild(paragraph);',
  '    });',
  '}',
  '',
  'export function serializeRichTextNode(node) {',
  '    if (node.nodeType === 1) {',
  '        return node.outerHTML;',
  '    }',
  '    if (node.nodeType === 3) {',
  "        return escapeRichTextText(node.nodeValue || '');",
  '    }',
  "    return '';",
  '}',
  '',
  'export function readInlineHtml(element) {',
  "    let html = '';",
  '    Array.prototype.slice.call(element.childNodes).forEach((node) => {',
  '        if (node.nodeType === 1) {',
  '            const child = node;',
  "            if (child.tagName === 'UL' || child.tagName === 'OL') {",
  '                return;',
  '            }',
  "            if (child.tagName === 'P') {",
  '                html += child.innerHTML;',
  '                return;',
  '            }',
  '        }',
  '        html += serializeRichTextNode(node);',
  '    });',
  "    return html.replace(/^\\s+|\\s+$/g, '');",
  '}',
  '',
  'export function isQuillSimpleList(list) {',
  "    if (list.hasAttribute('start')) {",
  '        return false;',
  '    }',
  '    const items = Array.prototype.slice.call(list.children);',
  '    for (let i = 0; i < items.length; i += 1) {',
  '        const item = items[i];',
  "        if (item.tagName !== 'LI') {",
  '            return false;',
  '        }',
  '        const children = Array.prototype.slice.call(item.childNodes);',
  '        let paragraphs = 0;',
  '        let nested = null;',
  '        for (let j = 0; j < children.length; j += 1) {',
  '            const child = children[j];',
  '            if (isRichTextInlineNode(child)) {',
  '                if (nested && !isBlankTextNode(child)) {',
  '                    return false;',
  '                }',
  '                continue;',
  '            }',
  '            const tag = child.tagName;',
  "            if (tag === 'P') {",
  '                paragraphs += 1;',
  '                if (paragraphs > 1 || nested) {',
  '                    return false;',
  '                }',
  '                continue;',
  '            }',
  "            if ((tag === 'UL' || tag === 'OL') && !nested) {",
  '                nested = child;',
  '                continue;',
  '            }',
  '            return false;',
  '        }',
  '        if (nested && !isQuillSimpleList(nested)) {',
  '            return false;',
  '        }',
  '    }',
  '    return true;',
  '}',
  '',
  'export function flattenListForQuill(list) {',
  "    let html = '<ol>';",
  '    const walk = (node, indent) => {',
  "        const type = node.tagName === 'OL' ? 'ordered' : 'bullet';",
  '        Array.prototype.slice.call(node.children).forEach((item) => {',
  "            if (item.tagName !== 'LI') {",
  '                return;',
  '            }',
  '            const indentClass = indent > 0 ? ` class="${QUILL_INDENT_CLASS_PREFIX}${indent}"` : \'\';',
  '            html += `<li ${QUILL_LIST_ITEM_ATTR}="${type}"${indentClass}>${readInlineHtml(item)}</li>`;',
  '            Array.prototype.slice.call(item.children).forEach((child) => {',
  "                if (child.tagName === 'UL' || child.tagName === 'OL') {",
  '                    walk(child, indent + 1);',
  '                }',
  '            });',
  '        });',
  '    };',
  '    walk(list, 0);',
  "    return html + '</ol>';",
  '}',
  '',
  'export function isQuillSimpleBlockquote(quote) {',
  '    const children = Array.prototype.slice.call(quote.childNodes);',
  '    for (let i = 0; i < children.length; i += 1) {',
  '        const child = children[i];',
  '        if (isRichTextInlineNode(child)) {',
  '            continue;',
  '        }',
  "        if (child.tagName !== 'P') {",
  '            return false;',
  '        }',
  '    }',
  '    return true;',
  '}',
  '',
  'export function blockquoteLinesForQuill(quote) {',
  '    const lines = [];',
  "    let pending = '';",
  '    const flush = () => {',
  '        if (/\\S/.test(pending)) {',
  "            lines.push(pending.replace(/^\\s+|\\s+$/g, ''));",
  '        }',
  "        pending = '';",
  '    };',
  '    Array.prototype.slice.call(quote.childNodes).forEach((node) => {',
  "        if (node.nodeType === 1 && node.tagName === 'P') {",
  '            flush();',
  '            lines.push(node.innerHTML);',
  '            return;',
  '        }',
  '        pending += serializeRichTextNode(node);',
  '    });',
  '    flush();',
  "    return lines.map((line) => `<blockquote>${line}</blockquote>`).join('');",
  '}',
  '',
  'export function protectedKindForElement(element) {',
  '    const tag = element.tagName;',
  "    if (tag === 'TABLE') {",
  "        return 'table';",
  '    }',
  "    if (tag === 'PRE') {",
  "        return 'code';",
  '    }',
  "    if (tag === 'ASIDE' && hasClass(element, CALLOUT_CLASS)) {",
  "        return 'callout';",
  '    }',
  "    if (tag === 'UL' || tag === 'OL') {",
  "        return 'list';",
  '    }',
  "    if (tag === 'BLOCKQUOTE') {",
  "        return 'quote';",
  '    }',
  "    return 'html';",
  '}',
  '',
  'export function toEditorHtml(storedHtml) {',
  '    const body = parseRichTextFragment(normalizeLegacyRichTextHtml(storedHtml));',
  "    let html = '';",
  '    Array.prototype.slice.call(body.childNodes).forEach((node) => {',
  '        if (node.nodeType === 3) {',
  "            if (/\\S/.test(node.nodeValue || '')) {",
  "                html += '<p>' + escapeRichTextText(node.nodeValue || '') + '</p>';",
  '            }',
  '            return;',
  '        }',
  '        if (node.nodeType !== 1) {',
  '            return;',
  '        }',
  '        const element = node;',
  '        const tag = element.tagName;',
  "        if (tag === 'P' || /^H[1-6]$/.test(tag)) {",
  '            html += element.outerHTML;',
  '            return;',
  '        }',
  '        if (isRichTextInlineNode(element)) {',
  "            html += '<p>' + element.outerHTML + '</p>';",
  '            return;',
  '        }',
  "        if (tag === 'DIV' && hasClass(element, PROTECTED_BLOCK_CLASS)) {",
  '            html += element.outerHTML;',
  '            return;',
  '        }',
  "        if (tag === 'FIGURE' &&",
  '            (hasClass(element, RICH_TEXT_IMAGE_CLASS) || hasClass(element, RICH_TEXT_EMBED_CLASS))) {',
  '            html += element.outerHTML;',
  '            return;',
  '        }',
  "        if ((tag === 'UL' || tag === 'OL') && isQuillSimpleList(element)) {",
  '            html += flattenListForQuill(element);',
  '            return;',
  '        }',
  "        if (tag === 'BLOCKQUOTE' && isQuillSimpleBlockquote(element)) {",
  '            html += blockquoteLinesForQuill(element);',
  '            return;',
  '        }',
  '        html += buildProtectedBlockHtml(protectedKindForElement(element), element.outerHTML);',
  '    });',
  '    return html;',
  '}',
  '',
  'export function fromEditorHtml(editorHtml) {',
  '    const body = parseRichTextFragment(editorHtml);',
  '    Array.prototype.slice',
  "        .call(body.querySelectorAll('.' + PROTECTED_BLOCK_CLASS))",
  '        .forEach((wrapper) => {',
  '        const parent = wrapper.parentNode;',
  '        if (!parent) {',
  '            return;',
  '        }',
  '        while (wrapper.firstChild) {',
  '            parent.insertBefore(wrapper.firstChild, wrapper);',
  '        }',
  '        parent.removeChild(wrapper);',
  '    });',
  '    const normalized = parseRichTextFragment(normalizeLegacyRichTextHtml(body.innerHTML));',
  '    unwrapSingleParagraphListItems(normalized);',
  '    wrapBareBlockquoteContent(normalized);',
  '    normalizeLinkTargets(normalized);',
  '    stripInterBlockWhitespace(normalized);',
  '    return trimEmptyEdgeParagraphs(normalized.innerHTML);',
  '}',
  '',
  'export function toCanonicalRichTextHtml(html) {',
  '    return fromEditorHtml(html);',
  '}',
  '',
  'export function trimEmptyEdgeParagraphs(html) {',
  '    return html',
  "        .replace(/^(?:\\s*<p>(?:<br\\s*\\/?>|\\s|&nbsp;)*<\\/p>)+/, '')",
  "        .replace(/(?:<p>(?:<br\\s*\\/?>|\\s|&nbsp;)*<\\/p>\\s*)+$/, '');",
  '}',
  '',
  'export function normalizeLegacyRichTextHtml(html) {',
  "    let out = String(html || '');",
  '    out = out.replace(/<span class="ql-ui"[^>]*>(?:<\\/span>)?/g, \'\');',
  "    out = out.replace(/<(ol|ul)(\\s[^>]*)?>((?:(?!<\\/?(?:ol|ul)\\b)[\\s\\S])*)<\\/\\1>/g, (match, _tag, _attrs, inner) => inner.indexOf(QUILL_LIST_ITEM_ATTR + '=') === -1 ? match : rebuildQuillListHtml(inner));",
  '    out = out.replace(/<div class="ql-code-block-container"[^>]*>((?:\\s*<div class="ql-code-block"[^>]*>[\\s\\S]*?<\\/div>)*)\\s*<\\/div>/g, (_match, inner) => rebuildQuillCodeBlockHtml(inner));',
  '    out = out.replace(/<pre data-language="([^"]*)">\\n?([\\s\\S]*?)\\n?<\\/pre>/g, (_match, language, code) => buildCodeBlockHtml(language, code, true));',
  '    out = out.replace(/((?:<blockquote>(?:(?!<\\/?blockquote\\b)[\\s\\S])*<\\/blockquote>\\s*)+)/g, (run) => mergeBlockquoteLines(run));',
  "    out = out.replace(/(\\S)(?:&nbsp;| )(?=\\S)/g, '$1 ');",
  '    return out;',
  '}',
  '',
  'export function rebuildQuillListHtml(innerHtml) {',
  '    const items = [];',
  '    const pattern = /<li\\b([^>]*)>([\\s\\S]*?)<\\/li>/g;',
  '    let match = pattern.exec(innerHtml);',
  '    while (match) {',
  '        const attrs = match[1];',
  '        const typeMatch = /data-list="([^"]*)"/.exec(attrs);',
  '        const indentMatch = /ql-indent-(\\d+)/.exec(attrs);',
  '        items.push({',
  "            type: typeMatch && typeMatch[1] === 'ordered' ? 'ordered' : 'bullet',",
  '            indent: indentMatch ? parseInt(indentMatch[1], 10) : 0,',
  "            html: match[2].replace(/^\\s+|\\s+$/g, ''),",
  '        });',
  '        match = pattern.exec(innerHtml);',
  '    }',
  '    if (!items.length) {',
  "        return '';",
  '    }',
  '    const render = (from, level) => {',
  "        let html = '';",
  '        let i = from;',
  "        let openType = '';",
  '        const close = () => {',
  '            if (openType) {',
  "                html += openType === 'ordered' ? '</ol>' : '</ul>';",
  "                openType = '';",
  '            }',
  '        };',
  '        while (i < items.length) {',
  '            const item = items[i];',
  '            if (item.indent < level) {',
  '                break;',
  '            }',
  '            if (item.indent > level) {',
  '                // A deeper line with nothing above it reads as this level.',
  '                item.indent = level;',
  '            }',
  '            if (openType !== item.type) {',
  '                close();',
  '                openType = item.type;',
  "                html += openType === 'ordered' ? '<ol>' : '<ul>';",
  '            }',
  "            html += '<li>' + item.html;",
  '            i += 1;',
  '            if (i < items.length && items[i].indent > level) {',
  '                const nested = render(i, level + 1);',
  '                html += nested.html;',
  '                i = nested.next;',
  '            }',
  "            html += '</li>';",
  '        }',
  '        close();',
  '        return { html, next: i };',
  '    };',
  '    return render(0, 0).html;',
  '}',
  '',
  'export function rebuildQuillCodeBlockHtml(innerHtml) {',
  '    const lines = [];',
  "    let language = '';",
  '    const pattern = /<div class="ql-code-block"([^>]*)>([\\s\\S]*?)<\\/div>/g;',
  '    let match = pattern.exec(innerHtml);',
  '    while (match) {',
  '        const languageMatch = /data-language="([^"]*)"/.exec(match[1]);',
  '        if (languageMatch && !language) {',
  '            language = languageMatch[1];',
  '        }',
  "        lines.push(match[2] === '<br>' ? '' : match[2]);",
  '        match = pattern.exec(innerHtml);',
  '    }',
  "    return buildCodeBlockHtml(language, lines.join('\\n'), true);",
  '}',
  '',
  'export function mergeBlockquoteLines(run) {',
  '    const lines = [];',
  '    const pattern = /<blockquote>([\\s\\S]*?)<\\/blockquote>/g;',
  '    let match = pattern.exec(run);',
  '    while (match) {',
  '        if (/<(?:p|ul|ol|div|pre|table|aside|figure|h[1-6])\\b/.test(match[1])) {',
  '            return run;',
  '        }',
  '        lines.push(match[1]);',
  '        match = pattern.exec(run);',
  '    }',
  "    return '<blockquote>' + lines.map((line) => '<p>' + line + '</p>').join('') + '</blockquote>';",
  '}',
  '',
].join('\n')
