import type { PaymentDriverId } from './payment-drivers-scope'

/**
 * Emits `utils/payments/index.js`: the one door to the store's payment
 * drivers. Each driver is required by a literal path so the Next.js bundler
 * packs exactly the providers this store uses, and built once per process.
 */
export const generatePaymentRegistryCode = (driverIds: readonly PaymentDriverId[]): string => {
  const factories = driverIds
    .map((id) => `  ${JSON.stringify(id)}: require('./drivers/${id}'),`)
    .join('\n')
  return `'use strict';
/**
 * Payment driver registry. Generated by TeleportHQ — changes are overwritten on the next export.
 */
var core = require('./core');

var factories = {
${factories}
};

var instances = {};

/** The driver for \`providerId\`, or null when this store carries none for it. */
function get(providerId) {
  var id = String(providerId == null ? '' : providerId).trim().toLowerCase();
  if (!Object.prototype.hasOwnProperty.call(factories, id)) {
    return null;
  }
  if (!instances[id]) {
    instances[id] = factories[id](core);
  }
  return instances[id];
}

module.exports = { get: get, ids: Object.keys(factories), core: core };
`
}
