import {
  UIDLPageTransition,
  UIDLPageTransitionAnimation,
  UIDLPageTransitionPreset,
  UIDLPageTransitionRegion,
} from '@teleporthq/teleport-types'

export interface ResolvedViewTransition {
  preset: UIDLPageTransitionPreset
  regions: Record<string, ResolvedRegion>
  reducedMotion: 'instant' | 'respect-preset'
  customCSS?: string
}

export interface ResolvedRegion {
  role: 'freeze' | 'animate'
  exit?: ResolvedAnimation
  enter?: ResolvedAnimation
}

export interface ResolvedAnimation {
  name: string
  keyframes: Record<string, Record<string, string | number>>
  duration: number
  easing: string
  delay: number
}

const DEFAULT_FLIPPING_NAME = 'main-page'
const DEFAULT_FROZEN_NAMES = ['navbar', 'page-stack']

export const resolvePageTransition = (config: UIDLPageTransition): ResolvedViewTransition => {
  const preset: UIDLPageTransitionPreset = config.preset ?? 'book-flip'
  const baseRegions = getPresetRegions(preset)
  const mergedRegions: Record<string, ResolvedRegion> = {}

  for (const [name, region] of Object.entries(baseRegions)) {
    mergedRegions[name] = cloneRegion(region)
  }

  if (config.regions) {
    for (const [name, override] of Object.entries(config.regions)) {
      mergedRegions[name] = mergeRegion(mergedRegions[name], override, preset, name)
    }
  }

  applyTopLevelOverrides(mergedRegions, config)

  for (const [name, region] of Object.entries(mergedRegions)) {
    if (region.role === 'animate' && !region.exit && !region.enter) {
      throw new Error(
        `View Transition: animate region "${name}" has no keyframes. ` +
          `Either use a built-in preset or supply keyframes via config.regions[name].exit/enter.keyframes.`
      )
    }
  }

  return {
    preset,
    regions: mergedRegions,
    reducedMotion: config.reducedMotion ?? 'instant',
    customCSS: config.customCSS,
  }
}

export const buildViewTransitionCSS = (resolved: ResolvedViewTransition): string => {
  const blocks: string[] = []

  blocks.push('/* View Transition API — generated by teleporthq */')
  blocks.push('::view-transition-old(root),\n::view-transition-new(root) {\n  animation: none;\n}')

  for (const [name, region] of Object.entries(resolved.regions)) {
    if (region.role === 'freeze') {
      blocks.push(
        `::view-transition-old(${name}),\n::view-transition-new(${name}) {\n  animation: none;\n}`
      )
    }
  }

  const keyframeBlocks: string[] = []
  const animationBlocks: string[] = []

  for (const [name, region] of Object.entries(resolved.regions)) {
    if (region.role !== 'animate') {
      continue
    }
    if (region.exit) {
      keyframeBlocks.push(renderKeyframes(region.exit))
      animationBlocks.push(
        `  ::view-transition-old(${name}) {\n    animation: ${renderAnimationShorthand(
          region.exit
        )};\n    transform-origin: left center;\n  }`
      )
    }
    if (region.enter) {
      keyframeBlocks.push(renderKeyframes(region.enter))
      animationBlocks.push(
        `  ::view-transition-new(${name}) {\n    animation: ${renderAnimationShorthand(
          region.enter
        )};\n  }`
      )
    }
  }

  if (keyframeBlocks.length > 0) {
    blocks.push(keyframeBlocks.join('\n\n'))
  }

  if (animationBlocks.length > 0) {
    const mediaQuery =
      resolved.reducedMotion === 'respect-preset'
        ? ''
        : '@media (prefers-reduced-motion: no-preference) '
    blocks.push(`${mediaQuery}{\n${animationBlocks.join('\n')}\n}`.trimStart())
  }

  if (resolved.customCSS) {
    blocks.push(resolved.customCSS.trim())
  }

  return blocks.join('\n\n') + '\n'
}

const renderKeyframes = (anim: ResolvedAnimation): string => {
  const lines: string[] = [`@keyframes ${anim.name} {`]
  for (const [stop, decls] of Object.entries(anim.keyframes)) {
    lines.push(`  ${stop} {`)
    for (const [prop, value] of Object.entries(decls)) {
      lines.push(`    ${prop}: ${value};`)
    }
    lines.push('  }')
  }
  lines.push('}')
  return lines.join('\n')
}

const renderAnimationShorthand = (anim: ResolvedAnimation): string => {
  const parts = [`${anim.name}`, `${anim.duration}ms`, anim.easing]
  if (anim.delay > 0) {
    parts.push(`${anim.delay}ms`)
  }
  parts.push('both')
  return parts.join(' ')
}

const cloneRegion = (region: ResolvedRegion): ResolvedRegion => ({
  role: region.role,
  exit: region.exit
    ? { ...region.exit, keyframes: cloneKeyframes(region.exit.keyframes) }
    : undefined,
  enter: region.enter
    ? { ...region.enter, keyframes: cloneKeyframes(region.enter.keyframes) }
    : undefined,
})

const cloneKeyframes = (
  keyframes: Record<string, Record<string, string | number>>
): Record<string, Record<string, string | number>> => {
  const out: Record<string, Record<string, string | number>> = {}
  for (const [stop, decls] of Object.entries(keyframes)) {
    out[stop] = { ...decls }
  }
  return out
}

const mergeRegion = (
  base: ResolvedRegion | undefined,
  override: UIDLPageTransitionRegion,
  preset: UIDLPageTransitionPreset,
  name: string
): ResolvedRegion => {
  const role = override.role
  if (role === 'freeze') {
    return { role: 'freeze' }
  }

  const exit = mergeAnimation(base?.exit, override.exit, defaultExitName(preset, name))
  const enter = mergeAnimation(base?.enter, override.enter, defaultEnterName(preset, name))

  if (!exit && !enter) {
    throw new Error(
      `View Transition: animate region "${name}" has no keyframes. ` +
        `Either use a built-in preset or supply keyframes via config.regions[name].exit/enter.keyframes.`
    )
  }

  return { role: 'animate', exit, enter }
}

const mergeAnimation = (
  base: ResolvedAnimation | undefined,
  override: UIDLPageTransitionAnimation | undefined,
  fallbackName: string
): ResolvedAnimation | undefined => {
  if (!base && !override) {
    return undefined
  }
  const merged: ResolvedAnimation = {
    name: override?.name ?? base?.name ?? fallbackName,
    keyframes: override?.keyframes ?? (base ? cloneKeyframes(base.keyframes) : {}),
    duration: override?.duration ?? base?.duration ?? 300,
    easing: override?.easing ?? base?.easing ?? 'ease',
    delay: override?.delay ?? base?.delay ?? 0,
  }
  if (Object.keys(merged.keyframes).length === 0) {
    throw new Error(
      `View Transition: animate region "${fallbackName}" has no keyframes. ` +
        `Either use a built-in preset or supply keyframes via config.regions[name].exit/enter.keyframes.`
    )
  }
  return merged
}

const applyTopLevelOverrides = (
  regions: Record<string, ResolvedRegion>,
  config: UIDLPageTransition
): void => {
  for (const region of Object.values(regions)) {
    if (region.role !== 'animate') {
      continue
    }
    if (region.exit) {
      if (config.duration?.exit !== undefined) {
        region.exit.duration = config.duration.exit
      }
      if (config.easing?.exit !== undefined) {
        region.exit.easing = config.easing.exit
      }
    }
    if (region.enter) {
      if (config.duration?.enter !== undefined) {
        region.enter.duration = config.duration.enter
      }
      if (config.easing?.enter !== undefined) {
        region.enter.easing = config.easing.enter
      }
      if (config.enterDelay !== undefined) {
        region.enter.delay = config.enterDelay
      }
    }
  }
}

const defaultExitName = (preset: UIDLPageTransitionPreset, regionName: string) =>
  `${preset}-${regionName}-exit`
const defaultEnterName = (preset: UIDLPageTransitionPreset, regionName: string) =>
  `${preset}-${regionName}-enter`

const getPresetRegions = (preset: UIDLPageTransitionPreset): Record<string, ResolvedRegion> => {
  switch (preset) {
    case 'book-flip':
      return bookFlipRegions()
    case 'fade':
      return fadeRegions()
    case 'slide':
      return slideRegions()
    case 'custom':
      return { [DEFAULT_FLIPPING_NAME]: { role: 'animate' } }
    default:
      return { [DEFAULT_FLIPPING_NAME]: { role: 'animate' } }
  }
}

const frozenRegions = (): Record<string, ResolvedRegion> => {
  const out: Record<string, ResolvedRegion> = {}
  for (const name of DEFAULT_FROZEN_NAMES) {
    out[name] = { role: 'freeze' }
  }
  return out
}

const bookFlipRegions = (): Record<string, ResolvedRegion> => ({
  ...frozenRegions(),
  [DEFAULT_FLIPPING_NAME]: {
    role: 'animate',
    exit: {
      name: 'tlp-page-flip-exit',
      duration: 520,
      easing: 'cubic-bezier(0.4, 0, 0.9, 0.6)',
      delay: 0,
      keyframes: {
        '0%': {
          transform: 'perspective(800px) rotateY(0deg)',
          filter: 'brightness(1)',
          opacity: 1,
        },
        '10%': {
          transform: 'perspective(800px) rotateY(4deg)',
          filter: 'brightness(1)',
        },
        '52%': {
          filter: 'brightness(0.7)',
        },
        '74%': {
          opacity: 1,
        },
        '100%': {
          transform: 'perspective(800px) rotateY(-90deg)',
          filter: 'brightness(0.08)',
          opacity: 0,
        },
      },
    },
    enter: {
      name: 'tlp-page-reveal',
      duration: 300,
      easing: 'cubic-bezier(0.2, 0, 0, 1)',
      delay: 460,
      keyframes: {
        from: {
          opacity: 0,
          transform: 'perspective(800px) rotateY(-6deg)',
          filter: 'brightness(0.86)',
        },
        to: {
          opacity: 1,
          transform: 'perspective(800px) rotateY(0deg)',
          filter: 'brightness(1)',
        },
      },
    },
  },
})

const fadeRegions = (): Record<string, ResolvedRegion> => ({
  ...frozenRegions(),
  [DEFAULT_FLIPPING_NAME]: {
    role: 'animate',
    exit: {
      name: 'tlp-page-fade-exit',
      duration: 200,
      easing: 'ease-out',
      delay: 0,
      keyframes: {
        from: { opacity: 1 },
        to: { opacity: 0 },
      },
    },
    enter: {
      name: 'tlp-page-fade-enter',
      duration: 200,
      easing: 'ease-in',
      delay: 200,
      keyframes: {
        from: { opacity: 0 },
        to: { opacity: 1 },
      },
    },
  },
})

const slideRegions = (): Record<string, ResolvedRegion> => ({
  ...frozenRegions(),
  [DEFAULT_FLIPPING_NAME]: {
    role: 'animate',
    exit: {
      name: 'tlp-page-slide-exit',
      duration: 300,
      easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
      delay: 0,
      keyframes: {
        from: { transform: 'translateX(0)', opacity: 1 },
        to: { transform: 'translateX(-30px)', opacity: 0 },
      },
    },
    enter: {
      name: 'tlp-page-slide-enter',
      duration: 300,
      easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
      delay: 300,
      keyframes: {
        from: { transform: 'translateX(30px)', opacity: 0 },
        to: { transform: 'translateX(0)', opacity: 1 },
      },
    },
  },
})
