import { generateDiscountEngineHelperCode } from '../../src/utils/discount-engine'

/**
 * The discount engine — the ES5 copy the published storefront runs.
 *
 * ⚠️ The fixture table below is SHARED with the editor/canvas copy in
 * teleport-gui (`features/e-commerce/utils/__tests__/discount-engine-parity.spec.ts`).
 * Two specs, one table: that is what proves the canvas, the checkout
 * workflows and the deployed store price the same discounts for the same
 * basket. Edit both tables or neither.
 */

interface DiscountEngineApi {
  normalizeRule: (row: Record<string, unknown>, source: string) => Record<string, unknown>
  linesFromCart: (items: unknown) => unknown[]
  resolve: (input: Record<string, unknown>) => Record<string, unknown>
  tender: (input: Record<string, unknown>) => Record<string, unknown>
}

const loadApi = (): DiscountEngineApi =>
  new Function(
    generateDiscountEngineHelperCode() +
      '\nreturn { normalizeRule: __deNormalizeRule, linesFromCart: __deLinesFromCart,' +
      ' resolve: __deResolve, tender: __deTender };'
  )() as DiscountEngineApi

// ── SHARED PARITY TABLE ─────────────────────────────────────────────────────
// Byte-identical in teleport-gui `discount-engine-parity.spec.ts` and
// teleport-code-generators `teleport-shared/__tests__/utils/discount-engine.ts`.
// Rows are what `/api/data/.../select` returns: strings for DECIMAL columns,
// driver booleans ('t'/'f'), nullable text. Cart items are `cart-get-items`
// lines (NET prices). Edit both tables or neither.
interface DiscountEngineFixture {
  name: string
  rules: Array<Record<string, unknown>>
  voucher: Record<string, unknown> | null
  cartItems: Array<Record<string, unknown>>
  taxRatePercent: number
  shippingPrice: number
  customer: { isFirstOrder: boolean | null }
  legacy: boolean
  /** The set the shopper picked, when the table states one. */
  choice?: string
  expected: {
    goodsDiscount: number
    shippingDiscount: number
    automaticGoodsDiscount: number
    voucherGoodsDiscount: number
    voucherApplied: boolean
    voucherRejection: string
    appliedIds: string[]
    eligibleProductIds: string[]
    options: Array<{ key: string; label: string; saving: number; selected: boolean }>
    choice: string
  }
}

interface GiftCardTenderFixture {
  name: string
  input: {
    balance: number
    total: number
    currency: string
    hasGiftCardLines: boolean
    hasRecurringLines?: boolean
    recurringTenderAllowed?: boolean
    hasRecurringTrial?: boolean
  }
  expected: { applied: number; amountDue: number }
}

const PARITY_CART = [
  { productId: 'p1', price: 100, quantity: 2, categoryIds: ['c1', 'root'] },
  { productId: 'p2', price: 50, quantity: 1, categoryIds: ['c2', 'root'] },
]

const PARITY_CART_WITH_GIFT_CARD = [
  ...PARITY_CART,
  { productId: 'g1', price: 40, quantity: 1, categoryIds: [], isGiftCard: 't' },
]

const PARITY_CART_WITH_SUBSCRIPTION = [
  ...PARITY_CART,
  { productId: 's1', price: 30, quantity: 1, categoryIds: ['root'], isRecurring: 'true' },
]

const NO_CUSTOMER = { isFirstOrder: null }

const AUTO_TEN_PERCENT = {
  id: 'a-ten',
  name: 'Ten percent',
  discount_type: 'percentage',
  discount_value: '10.00',
  applies_to_all_products: 't',
  priority: 1,
  stackable: 't',
}

const AUTO_FIFTY_FIXED = {
  id: 'a-fifty',
  name: 'Fifty off',
  discount_type: 'fixed',
  discount_value: '50.00',
  applies_to_all_products: true,
  priority: 2,
  stackable: 'true',
}

const VOUCHER_TEN_PERCENT = {
  id: 'v-ten',
  code: 'SAVE10',
  discount_type: 'percentage',
  discount_value: '10',
  applies_to_all_products: 't',
}

const AUTO_TWENTY_EXCLUSIVE = {
  id: 'a-twenty-x',
  name: 'Twenty off',
  discount_type: 'fixed',
  discount_value: '20',
  applies_to_all_products: 't',
  priority: 5,
  stackable: 'f',
}

const DISCOUNT_ENGINE_FIXTURES: DiscountEngineFixture[] = [
  {
    name: 'nothing applied',
    rules: [],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: [],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'voucher percentage on the whole cart',
    rules: [],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 25,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'voucher percentage on gross prices (tax added on top, per-unit rounding)',
    rules: [],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: [{ productId: 'p1', price: 23.79, quantity: 3 }],
    taxRatePercent: 19,
    shippingPrice: 0,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 8.49,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 8.49,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'voucher percentage above 100 clamps to the eligible gross',
    rules: [],
    voucher: { ...VOUCHER_TEN_PERCENT, discount_value: 150 },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 250,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 250,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'voucher fixed amount larger than the cart clamps',
    rules: [],
    voucher: { id: 'v-big', code: 'BIG', discount_type: 'fixed', discount_value: '999' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 250,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 250,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-big'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'voucher restricted to one product',
    rules: [],
    voucher: {
      id: 'v-p2',
      code: 'P2ONLY',
      discount_type: 'fixed',
      discount_value: '10',
      applies_to_all_products: 'f',
      product_ids: '["p2"]',
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 10,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 10,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-p2'],
      eligibleProductIds: ['p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'voucher restricted to a product not in the cart is a no-op',
    rules: [],
    voucher: {
      id: 'v-p9',
      code: 'P9',
      discount_type: 'percentage',
      discount_value: '10',
      applies_to_all_products: false,
      product_ids: ['p9'],
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'malformed product_ids reads as no restriction',
    rules: [],
    voucher: {
      id: 'v-bad',
      code: 'BAD',
      discount_type: 'fixed',
      discount_value: '5',
      applies_to_all_products: 'f',
      product_ids: '{not json',
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'free shipping voucher waives the fee',
    rules: [],
    voucher: { id: 'v-ship', code: 'SHIPFREE', discount_type: 'free_shipping', discount_value: 0 },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 7.5,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 7.5,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ship'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'free shipping voucher when shipping is already free is a no-op',
    rules: [],
    voucher: { id: 'v-ship', code: 'SHIPFREE', discount_type: 'free_shipping', discount_value: 0 },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 0,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'zero-quantity and empty carts price nothing',
    rules: [AUTO_TEN_PERCENT],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: [{ productId: 'p1', price: 100, quantity: 0 }],
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'automatic rule then a stackable voucher price sequentially',
    rules: [AUTO_TEN_PERCENT],
    voucher: { id: 'v-20', code: 'TWENTY', discount_type: 'fixed', discount_value: '20' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 45,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 20,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['a-ten', 'v-20'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'two automatic rules stack in priority order on the remaining value',
    rules: [AUTO_FIFTY_FIXED, AUTO_TEN_PERCENT],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 75,
      shippingDiscount: 0,
      automaticGoodsDiscount: 75,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten', 'a-fifty'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a percentage after a fixed rule prices the remainder',
    rules: [{ ...AUTO_FIFTY_FIXED, priority: 0 }, AUTO_TEN_PERCENT],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 70,
      shippingDiscount: 0,
      automaticGoodsDiscount: 70,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-fifty', 'a-ten'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'an exclusive automatic rule rejects the voucher',
    rules: [{ ...AUTO_TEN_PERCENT, stackable: 'f' }],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'not-stackable',
      appliedIds: ['a-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [
        { key: 'a-ten', label: 'Ten percent', saving: 25, selected: true },
        { key: 'combination', label: 'Code SAVE10', saving: 25, selected: false },
      ],
      choice: 'a-ten',
    },
  },
  {
    name: 'an exclusive voucher that saves less than the combination is refused',
    rules: [AUTO_TEN_PERCENT, AUTO_FIFTY_FIXED],
    voucher: {
      id: 'v-x',
      code: 'EXCL',
      discount_type: 'fixed',
      discount_value: '20',
      stackable: false,
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 75,
      shippingDiscount: 0,
      automaticGoodsDiscount: 75,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'not-stackable',
      appliedIds: ['a-ten', 'a-fifty'],
      eligibleProductIds: ['p1', 'p2'],
      options: [
        { key: 'voucher', label: 'Code EXCL', saving: 20, selected: false },
        { key: 'combination', label: 'Ten percent, Fifty off', saving: 75, selected: true },
      ],
      choice: 'combination',
    },
  },
  {
    name: 'an exclusive voucher that saves more than the combination replaces it',
    rules: [AUTO_TEN_PERCENT, AUTO_FIFTY_FIXED],
    voucher: {
      id: 'v-x',
      code: 'EXCL',
      discount_type: 'fixed',
      discount_value: '100',
      stackable: false,
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 100,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 100,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-x'],
      eligibleProductIds: ['p1', 'p2'],
      options: [
        { key: 'voucher', label: 'Code EXCL', saving: 100, selected: true },
        { key: 'combination', label: 'Ten percent, Fifty off', saving: 75, selected: false },
      ],
      choice: 'voucher',
    },
  },
  {
    name: 'an exclusive voucher that does not apply leaves the automatic rules alone',
    rules: [AUTO_TEN_PERCENT],
    voucher: {
      id: 'v-x9',
      code: 'EXCL9',
      discount_type: 'fixed',
      discount_value: '20',
      stackable: false,
      applies_to_all_products: 'f',
      product_ids: '["p9"]',
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: ['a-ten'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'an exclusive automatic rule that saves more wins over the combination',
    rules: [AUTO_TEN_PERCENT, { ...AUTO_FIFTY_FIXED, stackable: false }],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 50,
      shippingDiscount: 0,
      automaticGoodsDiscount: 50,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-fifty'],
      eligibleProductIds: [],
      options: [
        { key: 'a-fifty', label: 'Fifty off', saving: 50, selected: true },
        { key: 'combination', label: 'Ten percent', saving: 25, selected: false },
      ],
      choice: 'a-fifty',
    },
  },
  {
    name: 'an exclusive automatic rule wins over the combination whatever its priority',
    rules: [AUTO_TEN_PERCENT, { ...AUTO_FIFTY_FIXED, priority: 0, stackable: false }],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 50,
      shippingDiscount: 0,
      automaticGoodsDiscount: 50,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-fifty'],
      eligibleProductIds: [],
      options: [
        { key: 'a-fifty', label: 'Fifty off', saving: 50, selected: true },
        { key: 'combination', label: 'Ten percent', saving: 25, selected: false },
      ],
      choice: 'a-fifty',
    },
  },
  {
    name: 'the combination wins over an exclusive rule that saves less',
    rules: [
      AUTO_TEN_PERCENT,
      AUTO_FIFTY_FIXED,
      {
        id: 'a-sixty',
        name: 'Sixty off',
        discount_type: 'fixed',
        discount_value: '60',
        applies_to_all_products: 't',
        priority: 0,
        stackable: 'f',
      },
    ],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 75,
      shippingDiscount: 0,
      automaticGoodsDiscount: 75,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten', 'a-fifty'],
      eligibleProductIds: [],
      options: [
        { key: 'a-sixty', label: 'Sixty off', saving: 60, selected: false },
        { key: 'combination', label: 'Ten percent, Fifty off', saving: 75, selected: true },
      ],
      choice: 'combination',
    },
  },
  {
    name: 'a tie between an exclusive rule and the combination goes to the exclusive rule',
    rules: [
      AUTO_TEN_PERCENT,
      {
        id: 'a-25',
        name: 'Twenty-five off',
        discount_type: 'fixed',
        discount_value: '25',
        applies_to_all_products: 't',
        priority: 5,
        stackable: 'f',
      },
    ],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-25'],
      eligibleProductIds: [],
      options: [
        { key: 'a-25', label: 'Twenty-five off', saving: 25, selected: true },
        { key: 'combination', label: 'Ten percent', saving: 25, selected: false },
      ],
      choice: 'a-25',
    },
  },
  {
    name: 'a combinable voucher joins the combination an exclusive rule is measured against',
    rules: [AUTO_TEN_PERCENT, { ...AUTO_FIFTY_FIXED, stackable: 'f' }],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 50,
      shippingDiscount: 0,
      automaticGoodsDiscount: 50,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'not-stackable',
      appliedIds: ['a-fifty'],
      eligibleProductIds: ['p1', 'p2'],
      options: [
        { key: 'a-fifty', label: 'Fifty off', saving: 50, selected: true },
        { key: 'combination', label: 'Ten percent, Code SAVE10', saving: 47.5, selected: false },
      ],
      choice: 'a-fifty',
    },
  },
  {
    name: 'a combination with the voucher that saves more keeps the voucher',
    rules: [AUTO_TEN_PERCENT, { ...AUTO_FIFTY_FIXED, discount_value: '40', stackable: 'f' }],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 47.5,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 22.5,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['a-ten', 'v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [
        { key: 'a-fifty', label: 'Fifty off', saving: 40, selected: false },
        { key: 'combination', label: 'Ten percent, Code SAVE10', saving: 47.5, selected: true },
      ],
      choice: 'combination',
    },
  },
  {
    name: 'a voucher outside the chosen set is refused for its own reason when it would not apply anyway',
    rules: [{ ...AUTO_FIFTY_FIXED, stackable: 'f' }],
    voucher: { ...VOUCHER_TEN_PERCENT, min_order_value: '999' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 50,
      shippingDiscount: 0,
      automaticGoodsDiscount: 50,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'min-order',
      appliedIds: ['a-fifty'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'an exclusive free-shipping rule loses to a combination that saves more',
    rules: [
      AUTO_TEN_PERCENT,
      {
        id: 'a-ship-x',
        name: 'Free delivery',
        discount_type: 'free_shipping',
        discount_value: 0,
        applies_to_all_products: 't',
        priority: 0,
        stackable: 'f',
      },
    ],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten'],
      eligibleProductIds: [],
      options: [
        { key: 'a-ship-x', label: 'Free delivery', saving: 10, selected: false },
        { key: 'combination', label: 'Ten percent', saving: 25, selected: true },
      ],
      choice: 'combination',
    },
  },
  {
    name: 'minimum order value below the cart total rejects the voucher',
    rules: [],
    voucher: { ...VOUCHER_TEN_PERCENT, min_order_value: '300.00' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'min-order',
      appliedIds: [],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'minimum order value is met by the gross total',
    rules: [],
    voucher: { ...VOUCHER_TEN_PERCENT, min_order_value: '300.00' },
    cartItems: PARITY_CART,
    taxRatePercent: 20,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 30,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 30,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'minimum quantity counts eligible units',
    rules: [{ ...AUTO_TEN_PERCENT, min_quantity: 4 }],
    voucher: { ...VOUCHER_TEN_PERCENT, min_quantity: '3' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 25,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a first-order rule needs a customer known to be new',
    rules: [{ ...AUTO_TEN_PERCENT, first_order_only: 't' }],
    voucher: { ...VOUCHER_TEN_PERCENT, first_order_only: true },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'first-order',
      appliedIds: [],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a first-order rule applies to a new customer',
    rules: [{ ...AUTO_TEN_PERCENT, first_order_only: 't' }],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: { isFirstOrder: true },
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a category scope matches through the line categories',
    rules: [],
    voucher: {
      id: 'v-cat',
      code: 'CAT2',
      discount_type: 'percentage',
      discount_value: '10',
      applies_to_all_products: 'f',
      product_ids: null,
      category_ids: '["c2"]',
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 5,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 5,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-cat'],
      eligibleProductIds: ['p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a gift-card line is never eligible and never counts toward the minimum',
    rules: [],
    voucher: { ...VOUCHER_TEN_PERCENT, min_order_value: '260' },
    cartItems: PARITY_CART_WITH_GIFT_CARD,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'min-order',
      appliedIds: [],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a gift-card line is skipped by every rule',
    rules: [AUTO_TEN_PERCENT],
    voucher: null,
    cartItems: PARITY_CART_WITH_GIFT_CARD,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'buy 2 get 1 frees the cheapest unit of every full group',
    rules: [],
    voucher: {
      id: 'v-bogo',
      code: 'BOGO',
      discount_type: 'buy_x_get_y',
      discount_value: '0',
      buy_quantity: '2',
      get_quantity: '1',
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 50,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 50,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-bogo'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'buy 1 get 2 frees two units when the group is full',
    rules: [
      {
        id: 'a-bogo',
        name: 'Buy one get two',
        discount_type: 'buy_x_get_y',
        discount_value: 0,
        buy_quantity: 1,
        get_quantity: 2,
        applies_to_all_products: 't',
      },
    ],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 150,
      shippingDiscount: 0,
      automaticGoodsDiscount: 150,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-bogo'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'buy X get Y with too few units is a no-op',
    rules: [],
    voucher: {
      id: 'v-bogo4',
      code: 'BOGO4',
      discount_type: 'buy_x_get_y',
      discount_value: '0',
      buy_quantity: 3,
      get_quantity: 1,
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'free shipping is waived once however many rules say so',
    rules: [
      {
        id: 'a-ship',
        name: 'Free delivery',
        discount_type: 'free_shipping',
        discount_value: 0,
        applies_to_all_products: 't',
        priority: 1,
      },
    ],
    voucher: { id: 'v-ship', code: 'SHIPFREE', discount_type: 'free_shipping', discount_value: 0 },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 10,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: ['a-ship'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'legacy mode ignores automatic rules and conditions',
    rules: [AUTO_TEN_PERCENT],
    voucher: { ...VOUCHER_TEN_PERCENT, min_order_value: '999', first_order_only: 't' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: true,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 25,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'legacy mode prices a buy X get Y voucher as a no-op',
    rules: [],
    voucher: {
      id: 'v-bogo',
      code: 'BOGO',
      discount_type: 'buy_x_get_y',
      discount_value: '0',
      buy_quantity: '2',
      get_quantity: '1',
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: true,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'legacy mode ignores a category scope',
    rules: [],
    voucher: {
      id: 'v-cat',
      code: 'CAT2',
      discount_type: 'percentage',
      discount_value: '10',
      applies_to_all_products: 'f',
      product_ids: null,
      category_ids: '["c2"]',
    },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: true,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'an unknown discount type is a no-op',
    rules: [{ ...AUTO_TEN_PERCENT, discount_type: 'tiered' }],
    voucher: { ...VOUCHER_TEN_PERCENT, discount_type: 'mystery' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: 'no-op',
      appliedIds: [],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'stacked cent rounding: three cheap units at 10% then a fixed rule',
    rules: [AUTO_TEN_PERCENT, { ...AUTO_FIFTY_FIXED, discount_value: '0.30' }],
    voucher: null,
    cartItems: [{ productId: 'p1', price: 0.15, quantity: 3 }],
    taxRatePercent: 0,
    shippingPrice: 0,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 0.35,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0.35,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten', 'a-fifty'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a fixed rule never exceeds what is left of its lines',
    rules: [
      { ...AUTO_TEN_PERCENT, discount_value: '100' },
      { ...AUTO_FIFTY_FIXED, discount_value: '10' },
    ],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 250,
      shippingDiscount: 0,
      automaticGoodsDiscount: 250,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
  {
    name: 'a recurring line is never discounted and counts for no minimum',
    rules: [{ ...AUTO_TEN_PERCENT, min_order_value: '260' }],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: PARITY_CART_WITH_SUBSCRIPTION,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 25,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [],
      choice: '',
    },
  },
  {
    name: 'two sets save something: the shopper picks the exclusive rule over the larger combination',
    rules: [AUTO_TEN_PERCENT, AUTO_TWENTY_EXCLUSIVE],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    choice: 'a-twenty-x',
    expected: {
      goodsDiscount: 20,
      shippingDiscount: 0,
      automaticGoodsDiscount: 20,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-twenty-x'],
      eligibleProductIds: [],
      options: [
        { key: 'a-twenty-x', label: 'Twenty off', saving: 20, selected: true },
        { key: 'combination', label: 'Ten percent', saving: 25, selected: false },
      ],
      choice: 'a-twenty-x',
    },
  },
  {
    name: 'a choice naming no set falls back to the best set, and the options say so',
    rules: [AUTO_TEN_PERCENT, AUTO_TWENTY_EXCLUSIVE],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    choice: 'not-a-set',
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten'],
      eligibleProductIds: [],
      options: [
        { key: 'a-twenty-x', label: 'Twenty off', saving: 20, selected: false },
        { key: 'combination', label: 'Ten percent', saving: 25, selected: true },
      ],
      choice: 'combination',
    },
  },
  {
    name: 'the shopper keeps their exclusive voucher over a larger exclusive rule',
    rules: [AUTO_FIFTY_FIXED],
    voucher: { ...VOUCHER_TEN_PERCENT, stackable: 'f' },
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    choice: 'voucher',
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 0,
      voucherGoodsDiscount: 25,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [
        { key: 'voucher', label: 'Code SAVE10', saving: 25, selected: true },
        { key: 'combination', label: 'Fifty off', saving: 50, selected: false },
      ],
      choice: 'voucher',
    },
  },
  {
    name: 'a combinable voucher is named inside the combination option',
    rules: [AUTO_TEN_PERCENT, AUTO_TWENTY_EXCLUSIVE],
    voucher: VOUCHER_TEN_PERCENT,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    choice: 'combination',
    expected: {
      goodsDiscount: 47.5,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 22.5,
      voucherApplied: true,
      voucherRejection: '',
      appliedIds: ['a-ten', 'v-ten'],
      eligibleProductIds: ['p1', 'p2'],
      options: [
        { key: 'a-twenty-x', label: 'Twenty off', saving: 20, selected: false },
        { key: 'combination', label: 'Ten percent, Code SAVE10', saving: 47.5, selected: true },
      ],
      choice: 'combination',
    },
  },
  {
    name: 'one set saving something offers no choice, whatever the shopper says',
    rules: [AUTO_TEN_PERCENT],
    voucher: null,
    cartItems: PARITY_CART,
    taxRatePercent: 0,
    shippingPrice: 10,
    customer: NO_CUSTOMER,
    legacy: false,
    choice: 'combination',
    expected: {
      goodsDiscount: 25,
      shippingDiscount: 0,
      automaticGoodsDiscount: 25,
      voucherGoodsDiscount: 0,
      voucherApplied: false,
      voucherRejection: '',
      appliedIds: ['a-ten'],
      eligibleProductIds: [],
      options: [],
      choice: '',
    },
  },
]

const GIFT_CARD_TENDER_FIXTURES: GiftCardTenderFixture[] = [
  {
    name: 'the balance covers the whole order',
    input: { balance: 100, total: 80, currency: 'USD', hasGiftCardLines: false },
    expected: { applied: 80, amountDue: 0 },
  },
  {
    name: 'the balance covers part of the order',
    input: { balance: 25, total: 80, currency: 'USD', hasGiftCardLines: false },
    expected: { applied: 25, amountDue: 55 },
  },
  {
    name: 'a remainder under the minimum charge stays on the card',
    input: { balance: 79.8, total: 80, currency: 'USD', hasGiftCardLines: false },
    expected: { applied: 79.5, amountDue: 0.5 },
  },
  {
    name: 'the minimum charge follows the currency',
    input: { balance: 979, total: 1000, currency: 'JPY', hasGiftCardLines: false },
    expected: { applied: 950, amountDue: 50 },
  },
  {
    name: 'a total below the minimum charge is left to the provider',
    input: { balance: 0.1, total: 0.4, currency: 'USD', hasGiftCardLines: false },
    expected: { applied: 0, amountDue: 0.4 },
  },
  {
    name: 'a cart that buys a gift card cannot pay with one',
    input: { balance: 100, total: 80, currency: 'USD', hasGiftCardLines: true },
    expected: { applied: 0, amountDue: 80 },
  },
  {
    name: 'no balance, nothing applied',
    input: { balance: 0, total: 80, currency: 'EUR', hasGiftCardLines: false },
    expected: { applied: 0, amountDue: 80 },
  },
  {
    name: 'a zero total needs no tender',
    input: { balance: 30, total: 0, currency: 'EUR', hasGiftCardLines: false },
    expected: { applied: 0, amountDue: 0 },
  },
  {
    name: 'a recurring cart pays the first charge with the card, never below the minimum',
    input: {
      balance: 100,
      total: 30,
      currency: 'USD',
      hasGiftCardLines: false,
      hasRecurringLines: true,
      recurringTenderAllowed: true,
    },
    expected: { applied: 29.5, amountDue: 0.5 },
  },
  {
    name: 'a recurring cart takes a card smaller than the first charge in full',
    input: {
      balance: 10,
      total: 30,
      currency: 'USD',
      hasGiftCardLines: false,
      hasRecurringLines: true,
      recurringTenderAllowed: true,
    },
    expected: { applied: 10, amountDue: 20 },
  },
  {
    name: 'a recurring cart that starts with a free trial has nothing for a card to pay',
    input: {
      balance: 100,
      total: 30,
      currency: 'USD',
      hasGiftCardLines: false,
      hasRecurringLines: true,
      recurringTenderAllowed: true,
      hasRecurringTrial: true,
    },
    expected: { applied: 0, amountDue: 30 },
  },
  {
    name: 'a recurring cart on a checkout that cannot reduce the first charge pays nothing with a card',
    input: {
      balance: 100,
      total: 30,
      currency: 'USD',
      hasGiftCardLines: false,
      hasRecurringLines: true,
    },
    expected: { applied: 0, amountDue: 30 },
  },
]
// ── END SHARED PARITY TABLE ─────────────────────────────────────────────────

describe('discount engine — storefront copy against the shared parity table', () => {
  const api = loadApi()

  it.each(DISCOUNT_ENGINE_FIXTURES.map((fixture) => [fixture.name, fixture]))(
    '%s',
    (_name, fixture) => {
      const result = api.resolve({
        rules: fixture.rules.map((row) => api.normalizeRule(row, 'automatic')),
        voucher: fixture.voucher ? api.normalizeRule(fixture.voucher, 'voucher') : null,
        lines: api.linesFromCart(fixture.cartItems),
        taxRatePercent: fixture.taxRatePercent,
        shippingPrice: fixture.shippingPrice,
        customer: fixture.customer,
        legacy: fixture.legacy,
        choice: fixture.choice,
      })
      const applied = result.applied as Array<{ id: string }>
      expect({
        goodsDiscount: result.goodsDiscount,
        shippingDiscount: result.shippingDiscount,
        automaticGoodsDiscount: result.automaticGoodsDiscount,
        voucherGoodsDiscount: result.voucherGoodsDiscount,
        voucherApplied: result.voucherApplied,
        voucherRejection: result.voucherRejection,
        appliedIds: applied.map((entry) => entry.id),
        eligibleProductIds: result.eligibleProductIds,
        options: result.options,
        choice: result.choice,
      }).toEqual(fixture.expected)
    }
  )

  it.each(GIFT_CARD_TENDER_FIXTURES.map((fixture) => [fixture.name, fixture]))(
    'tender: %s',
    (_name, fixture) => {
      expect(api.tender(fixture.input)).toEqual(fixture.expected)
    }
  )

  it('is made of function expressions only, so it can be spliced into a serialized handler', () => {
    const source = generateDiscountEngineHelperCode()
    expect(source).not.toMatch(/^\s*function\s+__de/m)
    expect(source).toMatch(/var __deResolve = function \(input\)/)
    expect(source).not.toContain('`')
  })
})
