/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from '@stencil/core/internal'

export namespace Components {
  interface EditorComponent {
    dark: boolean
    uidl: string
  }
}

declare global {
  interface HTMLEditorComponentElement extends Components.EditorComponent, HTMLStencilElement {}
  var HTMLEditorComponentElement: {
    prototype: HTMLEditorComponentElement
    new (): HTMLEditorComponentElement
  }
  interface HTMLElementTagNameMap {
    'editor-component': HTMLEditorComponentElement
  }
}

declare namespace LocalJSX {
  interface EditorComponent extends JSXBase.HTMLAttributes<HTMLEditorComponentElement> {
    dark?: boolean
    uidl?: string
  }

  interface IntrinsicElements {
    'editor-component': EditorComponent
  }
}

export { LocalJSX as JSX }

declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}
