/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from '@stencil/core/internal'

export namespace Components {
  interface SimpleComponent {
    title: string
  }
  interface TeleportUidlRepl {
    dark: boolean
    uidl: string
  }
}

declare global {
  interface HTMLSimpleComponentElement extends Components.SimpleComponent, HTMLStencilElement {}
  var HTMLSimpleComponentElement: {
    prototype: HTMLSimpleComponentElement
    new (): HTMLSimpleComponentElement
  }

  interface HTMLTeleportUidlReplElement extends Components.TeleportUidlRepl, HTMLStencilElement {}
  var HTMLTeleportUidlReplElement: {
    prototype: HTMLTeleportUidlReplElement
    new (): HTMLTeleportUidlReplElement
  }
  interface HTMLElementTagNameMap {
    'simple-component': HTMLSimpleComponentElement
    'teleport-uidl-repl': HTMLTeleportUidlReplElement
  }
}

declare namespace LocalJSX {
  interface SimpleComponent extends JSXBase.HTMLAttributes<HTMLSimpleComponentElement> {
    title?: string
  }
  interface TeleportUidlRepl extends JSXBase.HTMLAttributes<HTMLTeleportUidlReplElement> {
    dark?: boolean
    uidl?: string
  }

  interface IntrinsicElements {
    'simple-component': SimpleComponent
    'teleport-uidl-repl': TeleportUidlRepl
  }
}

export { LocalJSX as JSX }

declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}
