name: CI for PR

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - run: yarn
    - run: yarn run lint
    - run: yarn run build
    - run: yarn run test:coverage
    - run: yarn run upload:coverage
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Building cms projects
      working-directory: packages/teleport-test
      run: yarn cms
    - name: Building Wordpress Project
      env:
          CMS_URL: ${{ secrets.WORDPRESS_URL }}
      working-directory: packages/teleport-test/dist/teleport-project-wordpress-cms
      run: |
        yarn
        yarn build
    - name: Building Contentful Project
      env:
          CMS_URL: ${{ secrets.CONTENTFUL_URL }}
          CMS_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      working-directory: packages/teleport-test/dist/teleport-project-contentful-cms
      run: |
        yarn
        yarn build
    - name: Building Strapi Porject
      env:
          CMS_URL: ${{ secrets.STRAPI_URL }}
          CMS_ACCESS_TOKEN: ${{ secrets.STRAPI_ACCESS_TOKEN }}
      working-directory: packages/teleport-test/dist/teleport-project-strapi-cms
      run: |
        yarn
        yarn build
    - name: Building Caisy Project
      env:
          CMS_URL: ${{ secrets.CAISY_URL }}
          CMS_ACCESS_TOKEN: ${{ secrets.CAISY_ACCESS_TOKEN }}
      working-directory: packages/teleport-test/dist/teleport-project-caisy-cms
      run: |
        yarn
        yarn build
    - name: Building Flotiq Project
      env:
          CMS_URL: ${{ secrets.FLOTIQ_URL }}
          CMS_ACCESS_TOKEN: ${{ secrets.FLOTIQ_ACCESS_TOKEN }}
      working-directory: packages/teleport-test/dist/teleport-project-flotiq-cms
      run: |
        yarn
        yarn build
